### ISSUE TITLE
first run experience of "./please --help" is not ideal

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#1026]
When I run "./please --help" it starts downloading a massive Docker image instead of giving me useful information. It looks like it's going to take 20-30min before I can actually interact with it.

**Comment by garbas** [comment]
ups this got out of control with latest update of our base image. as usual with dockerfiles I forgot to run a clean up command. The fix will come with #995 probably on Monday next week.

Before #995:
![screenshot-2018-4-6 mozillareleng services - docker hub](https://user-images.githubusercontent.com/20208/38427299-28136eb0-39b9-11e8-96ae-0eab532b0725.png)

After #995:
![screenshot-2018-4-6 mozillareleng services - docker hub 1](https://user-images.githubusercontent.com/20208/38427325-3c2daae6-39b9-11e8-9ca1-01c42f99c41d.png)

**Comment by garbas** [comment]
#995 is now merged and docker image is back to 380MB
