### ISSUE TITLE
How many CPUs should we use in docker image

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#1066]
we should use `--cpus` option when creating a docker container and most likely set containers that number to all cpus that are on the host (output of `nproc` command). Nix should automatically detect more cpus and use them.

@La0 @marco-c @rail do you have any thougts on this?

**Comment by rail** [comment]
Looking at the reference at https://docs.docker.com/engine/reference/run/:

> --cpus=0.000  Number of CPUs. Number is a fractional number. 0.000 means no limit.

It also looks like `/proc/cpuinfo` shows all CPUs inside the container.

Sounds like you want to limit the count of exposed CPUs, correct? Do we have a use case for this?
