### ISSUE TITLE
change author and author_email in all of the projects as it is set now in template

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#1069]
change `author` and `author_email` to

``
author='Mozilla Release Services Team',
author_email='release-services@mozilla.com',
``

in all python projects

**Comment by pgadige** [comment]
I'm working on this.

**Comment by marco-c** [comment]
For release management projects we should probably keep using `Mozilla Release Management` as author and `release-mgmt-analysis@mozilla.com` as author_email.

**Comment by pgadige** [comment]
So, all projects prefixed `releng-` are considered as release management projects?

**Comment by marco-c** [comment]
No, only `shipit-static-analysis`, `shipit-code-coverage`, `shipit-code-coverage-backend`, `shipit-uplift`, `shipit-bot-uplift`, `shipit-pulse-listener`.

**Comment by pgadige** [comment]
Thank you, @marco-c ! I shall take a note of this useful information. Being a newbie, I'm still exploring the codebase and gradually picking up the jargon specific to the project.

**Comment by marco-c** [comment]
> Thank you, @marco-c ! I shall take a note of this useful information. Being a newbie, I'm still exploring the codebase and gradually picking up the jargon specific to the project.

No worries, and thanks for picking this up ;)
