### ISSUE TITLE
shipit_code_coverage: Failure in triggering scheduled task

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1077]
This is still happening, even after #1045.
```
The hooks service was unable to create a task for hook project-releng/services-testing-shipit-code-coverage,
for which you are listed as owner.

The error was:
InterpreterError at template.payload.env[1]: unknown context value payload

Details:

{

"location": [
".payload",
".env",
"[1]"
],
"name": "InterpreterError"
}

The service will try again to create the task on the next iteration.

Thanks,
TaskCluster Automation

P.S. If you believe you have received this email in error, please hit reply to let us know.
```

The hook definition contains:
```
    "env": {
      "$merge": [
        {
          "APP_CHANNEL": "staging",
          "SSL_CERT_FILE": "/nix/store/y1la7mv3b95ka3hbfk4p9hpmxbfv6kka-nss-cacert-3.34.1/etc/ssl/certs/ca-bundle.crt"
        },
        {
          "else": {},
          "then": {
            "$eval": "payload"
          },
          "$if": "firedBy == 'triggerHook'"
        }
      ]
    },
```

Maybe the keys "$if", "then" and "else" have to be in order? CC @djmitche

**Comment by marco-c** [comment]
No, they don't have to be in order, as this works:
```Python
import jsone

template = {
    "payload": {
        "maxRunTime": 14400,
        "image": "marco",
        "artifacts": {},
        "val": {"$if": "firedBy == 'triggerHook'", "then": 3, "else": 2},
        "env": {"$merge": [
            {"a": 1, "b": 2},
            {"else": {}, "$if": "firedBy == 'triggerHook'", "then": {"$eval": "payload"}},
        ]}
    }
}
print(jsone.render(template, {'firedBy': 'triggerHook', 'payload': {} }))
print(jsone.render(template, {'firedBy': 'triggerHook', 'payload': {'REVISION': 'abc'} }))
print(jsone.render(template, {'firedBy': 'schedule'}))
```

**Comment by djmitche** [comment]
Hm, I've been able to trigger https://tools.taskcluster.net/hooks/garbage/test-context without any issue, so I think `payload` exists when `firedBy == 'triggerHook'`.

Note that the task template right now does not have the `$if` in it -- are you looking at a different hook definition?

**Comment by marco-c** [comment]
@djmitche yeah the problem happens when the hook is triggered by the scheduler, so payload isn't there but firedBy is 'schedule'.

This is the hook definition: https://tools.taskcluster.net/hooks/project-releng/services-staging-shipit-code-coverage.

**Comment by djmitche** [comment]
Hm, the original comment is about the "..-testing-.." hook.

**Comment by marco-c** [comment]
Oh, you're right, sorry. I hadn't noticed.

@garbas perhaps we shouldn't schedule the hook in the `testing` branch.

Anyway, this will be fixed once the testing branch is updated to master.
