### ISSUE TITLE
releng_frontend: Production build does not work without related services not deployed

### ISSUE THREAD

**Issue by La0** [mozilla-releng/services#1079]
As several projects are not deployed in production during @garbas PTO (see #1076), the production build of **releng_frontend** is invalid: several `--env` and `--csp` are missing.
Staging deployment is OK.

I have a script that fixes this temporarily by pushing a valid index.html on S3 with all the needed parameters (can't publish it as it neeeds access to TC production secrets).

We have two choices here:
- Restore deployment in production of tooltool, treestatus, ...
- Remove the production deployment of releng_frontend

**Comment by garbas** [comment]
@La0 thank you for fixing this.

If possible it would be nice to fix releng_frontend and keep not comment it out, since that would block any updates to trychooser.

could you share what the script fixed in index.html (eg. the diff between old/new index.html)

**Comment by La0** [comment]
@garbas The script is just deploying again **releng-frontend** but with all the necessary `--env` & `--csp`:

```shell

./please -vv tools deploy:S3 releng-frontend \
	--s3-bucket=releng-production-frontend \
	--taskcluster-secret=repo:github.com/mozilla-releng/services:branch:production \
 --channel=production \
 --no-interactive \
 --csp="https://login.taskcluster.net" \
 --csp="https://auth.taskcluster.net" \
 --csp="https://docs.mozilla-releng.net" \
 --csp="https://policy.notification.mozilla-releng.net" \
 --csp="https://identity.notification.mozilla-releng.net" \
 --env="release-version: 37" \
 --env="release-channel: production" \
 --env="releng-docs-url: https://docs.mozilla-releng.net" \
 --env="releng-notification-policy-url: https://policy.notification.mozilla-releng.net" \
 --env="releng-notification-identity-url: https://identity.notification.mozilla-releng.net" \

# MISSING: 
 --csp="https://clobberer.mozilla-releng.net" \
 --csp="https://tooltool.mozilla-releng.net" \
 --csp="https://treestatus.mozilla-releng.net" \
 --csp="https://mapper.mozilla-releng.net" \
 --csp="https://archiver.mozilla-releng.net" \
 --env="releng-clobberer-url: https://clobberer.mozilla-releng.net" \
 --env="releng-tooltool-url: https://tooltool.mozilla-releng.net" \
 --env="releng-treestatus-url: https://treestatus.mozilla-releng.net" \
 --env="releng-mapper-url: https://mapper.mozilla-releng.net" \
 --env="releng-archiver-url: https://archiver.mozilla-releng.net"

```

**Comment by La0** [comment]
A better solution is to edit the production Taskcluster task for releng-frontend deployment and add the missing lines. [Example task](https://tools.taskcluster.net/groups/P1Yoqq9PQbioXDHpbgvigA/) ran today in order to fix a broken deployment.

**Comment by garbas** [comment]
@La0 tnx for fixing this. i suppose a proper solution going forward would be to have "enable" option for each channel. then we don't have to comment out anything.

in #1178 i'm uncommenting tooltool and treestatus
