### ISSUE TITLE
Consider using Squash and Merge by default in PRs 

### ISSUE THREAD

**Issue by rail** [mozilla-releng/services#112]
This way we don't have any not working commits.

**Comment by garbas** [comment]
@rail i would say :+1: if this would be "squash and rebase".

also sometimes it actually make sense to have 2 commits instead of 1, right? or am i missing something.

Right now every PR needs to be approved, which means we can enforce this via conversation.

**Comment by rail** [comment]
I think it doesn't generate a merge commit, even though there is "Merge" in the name. I don't mind multiple commits, only if all of them are passing CI tests. Otherwise bisecting becomes useless.

**Comment by garbas** [comment]
I enabled all options how to merge PRs. now we have to use our own brain :)
