### ISSUE TITLE
shipit_code_coverage: the file zero_coverage_report.json contains some relative paths

### ISSUE THREAD

**Issue by calixteman** [mozilla-releng/services#1152]
For example:
gfx/skia/skia/include/ports/../private/SkTemplates.h
third_party/aom/aom_dsp/simd/./v128_intrinsics_x86.h

**Comment by marco-c** [comment]
I think we should do the cleanup in grcov, when parsing the gcda files.
I've opened https://github.com/marco-c/grcov/issues/100.

**Comment by marco-c** [comment]
(Luckily this is not a large problem, as it only affects a small subset of header files)
