### ISSUE TITLE
shipit_static_analysis: Enable Phabricator reviews in production

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#1166]
Our automated review bot is able to analyze Phabricator code reviews.

We should evaluate its results on staging, and once satisfied we should enable it in production (and evaluate it there as well).

TODO:

- [x] Ensure that our bot detects new Phabricator code reviews (on staging and production)
- [x] Ensure that our bot publishes automated reviews when it finds issues
- [x] Validate published reviews on staging (iterate if adjustments are needed)
  - [x] Ensure that `clang-tidy` and `eslint` issues work as well
- [x] Enable in production
- [x] Confirm that published reviews still look good/valuable in production
  - [x] Ensure that published reviews including C/C++ defects also look good/valuable (once #1263 is fixed)
- [x] As a drive-by, also validate comments on MozReview again, just in case

**Comment by jankeromnes** [comment]
So, running `shipit-static-analysis` a second time with:

```
export PHABRICATOR="324:PHID-DIFF-i4b753ptojloi2tjwm2z"
```

**Comment by jankeromnes** [comment]
The phabricator hook parameter issue should be fixed by 3b247846c3f8dae80532aa671421d2df96e241f5. Hopefully auto-reviews will now work on staging, allowing us to move on to review validation.

**Comment by jankeromnes** [comment]
Now automatically published reviews on staging! :tada: Thanks @marco-c and @garbas for the help, and especially @La0 for writing all the code! :stuck_out_tongue: 

Latest review on https://phabricator-dev.allizom.org/D324 was automatically submitted by the bot after I pushed a new revision, and you should have received an email titled:

    [staging] New Static Analysis Phabricator #645 - PHID-DIFF-y5cvex4pzvr6g4epqf3g

**Comment by jankeromnes** [comment]
Ok, in the latest review (which was automated), we appear to have `eslint` comments now, but still no `clang-tidy`.

The staging configuration looks like this:

```
shipit-static-analysis:
  [...]
  PUBLICATION: BEFORE_AFTER
  [...]
  ANALYZERS:
    - clang-tidy
    - clang-format
    - mozlint
```

From the logs, it looks like clang-tidy did run, but it's hard to tell exactly what happened (partly because clang-format adds a lot of noise).

Relevant log excerpts:

```
shipit_static_analysis.workflow: Run ClangTidy
shipit_static_analysis.clang.tidy: Available clang-tidy checks:
	
	[... a lot of checkers]

shipit_static_analysis.clang.tidy: Running static-analysis (cmd='gecko-env ./mach --log-no-times static-analysis check --header-filter=scroll.js|.arcconfig|prep_cif.c|menus.js|jsapi.cpp|gen_event_data.py|definitions.js --checks=-*,misc-forward-declaration-namespace,clang-analyzer-deadcode.DeadStores,clang-analyzer-security.FloatLoopCounter,clang-analyzer-security.insecureAPI.UncheckedReturn,clang-analyzer-security.insecureAPI.getpw,clang-analyzer-security.insecureAPI.mkstemp,clang-analyzer-security.insecureAPI.mktemp,clang-analyzer-security.insecureAPI.rand,clang-analyzer-security.insecureAPI.strcpy,clang-analyzer-security.insecureAPI.vfork,misc-argument-comment,misc-assert-side-effect,misc-suspicious-missing-comma,misc-suspicious-semicolon,misc-unused-using-decls,modernize-avoid-bind,modernize-loop-convert,modernize-raw-string-literal,modernize-redundant-void-arg,modernize-shrink-to-fit,modernize-use-equals-default,modernize-use-equals-delete,modernize-use-nullptr,modernize-use-override,mozilla-*,performance-for-range-copy,performance-inefficient-string-concatenation,performance-inefficient-vector-operation,performance-type-promotion-in-math-fn,performance-unnecessary-copy-initialization,performance-unnecessary-value-param,readability-container-size-empty,readability-else-after-return,readability-misleading-indentation,readability-redundant-control-flow,readability-redundant-smartptr-get,readability-redundant-string-cstr,readability-redundant-string-init,readability-uniqueptr-delete-release,modernize-use-auto,modernize-use-bool-literals devtools/client/shared/scroll.js .arcconfig js/src/ctypes/libffi/src/prep_cif.c devtools/client/menus.js js/src/jsapi.cpp toolkit/components/telemetry/gen_event_data.py devtools/client/definitions.js')
+ exec ./mach --log-no-times static-analysis check '--header-filter=scroll.js|.arcconfig|prep_cif.c|menus.js|jsapi.cpp|gen_event_data.py|definitions.js' '--checks=-*,misc-forward-declaration-namespace,clang-analyzer-deadcode.DeadStores,clang-analyzer-security.FloatLoopCounter,clang-analyzer-security.insecureAPI.UncheckedReturn,clang-analyzer-security.insecureAPI.getpw,clang-analyzer-security.insecureAPI.mkstemp,clang-analyzer-security.insecureAPI.mktemp,clang-analyzer-security.insecureAPI.rand,clang-analyzer-security.insecureAPI.strcpy,clang-analyzer-security.insecureAPI.vfork,misc-argument-comment,misc-assert-side-effect,misc-suspicious-missing-comma,misc-suspicious-semicolon,misc-unused-using-decls,modernize-avoid-bind,modernize-loop-convert,modernize-raw-string-literal,modernize-redundant-void-arg,modernize-shrink-to-fit,modernize-use-equals-default,modernize-use-equals-delete,modernize-use-nullptr,modernize-use-override,mozilla-*,performance-for-range-copy,performance-inefficient-string-concatenation,performance-inefficient-vector-operation,performance-type-promotion-in-math-fn,performance-unnecessary-copy-initialization,performance-unnecessary-value-param,readability-container-size-empty,readability-else-after-return,readability-misleading-indentation,readability-redundant-control-flow,readability-redundant-smartptr-get,readability-redundant-string-cstr,readability-redundant-string-init,readability-uniqueptr-delete-release,modernize-use-auto,modernize-use-bool-literals' devtools/client/shared/scroll.js .arcconfig js/src/ctypes/libffi/src/prep_cif.c devtools/client/menus.js js/src/jsapi.cpp toolkit/components/telemetry/gen_event_data.py devtools/client/definitions.js
```

I'm not sure what happened, as all analysis steps seem to be running in random order, I guess before and after the patch.

Maybe the problem is related to the `BEFORE_AFTER` behavior? I'll try to dig further in the email report soon, but I'm afraid that it is truncated because there are way too many `clang-format` comments.

Maybe we could temporarily disable `clang-format` on staging to better understand what's happening?

**Comment by La0** [comment]
By using #1209, i now get the following issues:

```
[warning] readability-else-after-return js/src/ctypes/libffi/src/prep_cif.c 88:3
[error] mozilla-dangling-on-temporary js/src/jsapi.cpp 131:39
[error] mozilla-dangling-on-temporary js/src/jsapi.cpp 132:38
[warning] modernize-redundant-void-arg js/src/jsapi.cpp 243:42
[warning] modernize-redundant-void-arg js/src/jsapi.cpp 647:29
[warning] modernize-raw-string-literal js/src/jsapi.cpp 1770:32
[warning] modernize-use-auto js/src/jsapi.cpp 3277:5
[warning] modernize-use-equals-default js/src/jsapi.cpp 3903:5
[warning] modernize-use-equals-default js/src/jsapi.cpp 3906:5
[warning] modernize-use-equals-default js/src/jsapi.cpp 5819:35
[warning] modernize-use-equals-default js/src/jsapi.cpp 7076:15
[warning] modernize-use-equals-default js/src/jsapi.cpp 7080:15
[warning] modernize-redundant-void-arg js/src/jsapi.cpp 7908:15
eslint issue error devtools/client/shared/scroll.js line 7
eslint issue error devtools/client/menus.js line 31
eslint issue error devtools/client/menus.js line 41
eslint issue error devtools/client/definitions.js line 7
flake8 issue error toolkit/components/telemetry/gen_event_data.py line 37
flake8 issue error toolkit/components/telemetry/gen_event_data.py line 37
flake8 issue error toolkit/components/telemetry/gen_event_data.py line 37
flake8 issue error toolkit/components/telemetry/gen_event_data.py line 57
```

**Comment by jankeromnes** [comment]
So, our bot seems to catch all the issues again (on staging), which is great.

However, yesterday's push to Phabricator staging didn't get any review comments.

I attempted another push today, watching the logs. I did find a bug with the email report (#1210), but his time the Phabricator comments *did* work. Maybe it's a race condition, but I guess we'll have to try again a few times to make sure it works consistently.

**Comment by jankeromnes** [comment]
Now testing on a new phabricator-dev revision: https://phabricator-dev.allizom.org/D431

Triggered analysis task: https://tools.taskcluster.net/groups/DFq61B7ISwaYdCYqUc6QCw/

Last try didn't post any `clang-tidy` comments. Let's see if this one does.

**Comment by jankeromnes** [comment]
I have a few nits about the automated review that was published to [D431](https://phabricator-dev.allizom.org/D431):

- [ ] off-by-one error on the lines a review comment is attached to (e.g. for a defect on line 7, the comment is attached to lines 7+8, placing one line too low)
- [ ] the bot missed 11/19 clang-tidy defects (that's 42% hit rate, which is not great):
  - `readability-else-after-return`
  - `misc-suspicious-missing-comma`
  - `readability-misleading-indentation`
  - `clang-analyzer-security.FloatLoopCounter`
  - `clang-analyzer-security.insecureAPI.UncheckedReturn`
  - `security.insecureAPI.gets`
  - `misc-suspicious-semicolon`
  - `modernize-redundant-void-arg`
  - `clang-analyzer-deadcode.DeadStores`
  - `performance-faster-string-find`
  - `performance-implicit-conversion-in-loop`
- [ ] the bot missed 1/9 mozlint defects:
  - `codespell`
- [ ] the bot reported 6 extra defects that were *not* in the patch (pre-existing issues, should not be reported):
  - `modernize-raw-string-literal`
  - `modernize-use-equals-default` * 5

**Comment by La0** [comment]
10 issues were found before applying the patch, as we are running with new `BEFORE_AFTER` mode on staging: 

```
Mach static analysis found some issues (nb=10)
Skipping clang-diagnostic-error: [error] clang-diagnostic-error js/src/ctypes/libffi/include/ffi_common.h 23:12
Found 3rd party code issue [warning] readability-else-after-return js/src/ctypes/libffi/src/prep_cif.c 88:3
Found in-tree code issue [warning] modernize-redundant-void-arg js/src/jsapi.cpp 608:29
Found in-tree code issue [warning] modernize-raw-string-literal js/src/jsapi.cpp 1675:32
Found in-tree code issue [warning] modernize-use-auto js/src/jsapi.cpp 3190:5
Found in-tree code issue [warning] modernize-use-equals-default js/src/jsapi.cpp 3816:5
Found in-tree code issue [warning] modernize-use-equals-default js/src/jsapi.cpp 3819:5
Found in-tree code issue [warning] modernize-use-equals-default js/src/jsapi.cpp 5732:35
Found in-tree code issue [warning] modernize-use-equals-default js/src/jsapi.cpp 6989:15
Found in-tree code issue [warning] modernize-use-equals-default js/src/jsapi.cpp 6993:15
Found in-tree code issue [warning] modernize-redundant-void-arg js/src/jsapi.cpp 7821:15
Skipping clang-diagnostic-error: [error] clang-diagnostic-error obj-x86_64-pc-linux-gnu/dist/system_wrappers/cstddef 3:15
```

**Comment by La0** [comment]
The codespell error is not in the [dictionary](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt) (depandent)

**Comment by sylvestre** [comment]
I created a PR https://github.com/codespell-project/codespell/pull/549 for the depandent thing

**Comment by La0** [comment]
I'll be working on the other issues this week, i'll update this ticket when i get some code

**Comment by jankeromnes** [comment]
Thanks @La0! Please ping me if I can help. :slightly_smiling_face:

**Comment by La0** [comment]
The review summary is generated by Phabricator, we only push [the same comment](https://github.com/mozilla-releng/services/blob/master/src/shipit_static_analysis/shipit_static_analysis/report/base.py#L127) as on Mozreview, without any extra infos about issues.

The [differential.createcomment](https://phabricator-dev.allizom.org/conduit/method/differential.createcomment/) is used to publish these comments.

I just looked at the Phabricator source code, and it seems we could [specify an action](https://github.com/phacility/phabricator/blob/master/src/applications/differential/conduit/DifferentialCreateCommentConduitAPIMethod.php#L61) based on the analysis result : 

* accept
* reject
* rethink
* resign
* request_review

The reques_review & reject seem interesting for our use case

**Comment by La0** [comment]
I published a [test review](https://phabricator-dev.allizom.org/D324#21841) from my local version fixing the offset lines + bug report link

**Comment by jankeromnes** [comment]
> The request_review & reject seem interesting for our use case

Indeed, thanks!

- However, I don't think we'll want to `reject` reviews, as that may be perceived as harsh (many reviewers often avoid using `r-` on a patch, and prefer clearing the review request instead).
- Also I don't think we should remove the `request_review` flag, because the developer may still want the requested person to have a look (e.g. a patch "[WIP] please comment on my general approach" may have lint issues, but the developer definitely still wants a human to take a look).

> I published a [test review](https://phabricator-dev.allizom.org/D324#21841) from my local version fixing the offset lines + bug report link

Thanks a lot! The bug report link looks good, but the comments still seem off by one line (e.g. the first `eslint: space-infix-ops` issue should be on line 7, but the latest comment is still on lines 7 & 8). Maybe we could ping the Conduit folks about this (and they may or may not forward it via our paid Phabricator support account).

**Comment by jankeromnes** [comment]
Thanks for merging the fixes!

But this issue is not quite done yet. (I'll close it when we've enabled Phabricator in production.)

**Comment by La0** [comment]
Sorry @jankeromnes, I did not want to close this issue, i used `refs` instead of `closes` thinking that would do the trick. There is indeed some work left !

**Comment by jankeromnes** [comment]
No worries! I think GitHub's heuristic triggered on the word "Fixes", followed by an issue number (regardless of the text in between). :stuck_out_tongue:

**Comment by jankeromnes** [comment]
In the TaskCluster staging secrets, I changed `PUBLICATION:` from `BEFORE_AFTER` to `IN_PATCH`, in order to use what production will use soon.

I then uploaded a new diff to https://phabricator-dev.allizom.org/D324, attempting to re-trigger the bot (with new staging code and `IN_PATCH`).

However, the new task https://tools.taskcluster.net/groups/AO98K3mTTJOKBLNQBMUyLA instantly failed with: `AssertionError: Specify a phabricator XOR mozreview parameters`.

**Comment by jankeromnes** [comment]
:warning: It turns out that there are several commits on `staging` that are not on `master`: https://github.com/mozilla-releng/services/compare/staging?expand=1

@La0 I would like to trigger a staging run of `shipit-static-analysis`, but it fails now. Could you please help me run another validation run? (on phabricator, with the exact code that will go to production tomorrow, and the correct staging configuration that also looks like production)

**Comment by jankeromnes** [comment]
I've force-pushed `master` to `staging` again, and I'm waiting for `shipit-static-analysis` to finish building before triggering another Phabricator analysis.

**Comment by jankeromnes** [comment]
`shipit-static-analysis` and `shipit-pulse-listener` were successfully built and deployed to staging, and I triggered another analysis.

This time the task went on longer, but it failed with:

```
 0:53.84 Reticulating splines...
 0:54.52 Traceback (most recent call last):
 0:54.52   File "/cache/sa-central/configure.py", line 123, in <module>
 0:54.52     sys.exit(main(sys.argv))
 0:54.52   File "/cache/sa-central/configure.py", line 34, in main
 0:54.52     return config_status(config)
 0:54.52   File "/cache/sa-central/configure.py", line 118, in config_status
 0:54.52     return config_status(args=[], **encode(sanitized_config, encoding))
 0:54.52   File "/cache/sa-central/python/mozbuild/mozbuild/config_status.py", line 143, in config_status
 0:54.52     definitions = list(definitions)
 0:54.52   File "/cache/sa-central/python/mozbuild/mozbuild/frontend/emitter.py", line 171, in emit
 0:54.52     for out in output:
 0:54.52   File "/cache/sa-central/python/mozbuild/mozbuild/frontend/reader.py", line 880, in read_topsrcdir
 0:54.52     for r in self.read_mozbuild(path, self.config):
 0:54.52   File "/cache/sa-central/python/mozbuild/mozbuild/frontend/reader.py", line 1047, in read_mozbuild
 0:54.52     raise bre
 0:54.52 mozbuild.frontend.reader.BuildReaderError:
 0:54.52 ==============================
 0:54.52 FATAL ERROR PROCESSING MOZBUILD FILE
 0:54.52 ==============================
 0:54.52 
 0:54.52 The error occurred while processing the following file:
 0:54.52 
 0:54.52     /cache/sa-central/toolkit/library/rust/gkrust-features.mozbuild
 0:54.52 
 0:54.52 This file was included as part of processing:
 0:54.52 
 0:54.52     /cache/sa-central/toolkit/library/gtest/rust/moz.build
 0:54.52 
 0:54.52 A moz.build file called the error() function.
 0:54.52 
 0:54.52 The error it encountered is:
 0:54.52 
 0:54.52     Builds on automation must use a version of rust that supports OOM hooking
 0:54.52 
 0:54.52 Correct the error condition and try again.
 0:54.52 
 1:06.46 *** Fix above errors and then restart with\
 1:06.46                "/nix/store/lhp5rw0dagi5mgqwr9i3x41240ba4ypz-gnumake-4.2.1/bin/make -f client.mk build"
 1:06.46 make: *** [client.mk:127: configure] Error 1
```

**Comment by marco-c** [comment]
For historical purposes: the problem was that we were using a version of Rust (1.27.0) which is not supported for automation on mozilla-central. We were not pinning Rust, so we inadvertently updated from 1.26.2 to 1.27.0 (this is now fixed by https://github.com/mozilla-releng/services/pull/1238).

**Comment by jankeromnes** [comment]
Thanks to Bastien's fix, I was finally able to run another analysis on staging, and the bot posted a new review to https://phabricator-dev.allizom.org/D324.

From what I see, it reveals the following problems (with the `IN_PATCH` heuristic):

- [ ] some comments are malformed (e.g. they include spurious output after the issue body, e.g. some unrelated warning, which looks like a clang-tidy parsing error)
- [ ] the bot missed 2/9 mozlint defects
  - `eslint: strict`
  - `codespell` ("maching")
- [ ] the bot missed 10/12 clang-tidy defects (basically it missed all clang-tidy defects except the `mozilla-*` ones):
  - `readability-else-after-return` (supposedly enabled)
  - `misc-suspicious-missing-comma` (supposedly enabled)
  - `readability-misleading-indentation` (supposedly enabled)
  - `clang-analyzer-security.FloatLoopCounter` (supposedly enabled)
  - `clang-analyzer-security.insecureAPI.UncheckedReturn` (supposedly enabled)
  - `misc-suspicious-semicolon` (supposedly enabled)
  - `modernize-redundant-void-arg` (supposedly enabled)
  - `clang-analyzer-deadcode.DeadStores` (supposedly enabled)
  - `performance-faster-string-find` (supposedly enabled now)
- [x] this time, bot reported didn't report the 6 extra defects that were *not* in the patch (pre-existing issues, should not be reported), so I conclude that it was a `BEFORE_AFTER` bug (i.e. #1236)

**Comment by abpostelnicu** [comment]
misc-suspicious-missing-comma didn't work because the initialiser list if < 5 - Let's use an official example from here https://github.com/llvm-mirror/clang-tools-extra/blob/release_50/test/clang-tidy/misc-suspicious-missing-comma.cpp

**Comment by jankeromnes** [comment]
Thanks a lot @abpostelnicu for figuring out the threshold! I've updated the list of undetected checks.

Still, the checks that are not ~~strikethrough~~ should have reported defects in the patch. I'm not sure why the bot *only* reported `mozilla-*` defects.

**Comment by jankeromnes** [comment]
I've updated our various checklists in this bug. Looking good! Thanks everyone for the hard work.

Now we only need to run analysis on **staging** one more time (I expect it to be the last), and then move on to validating production (which should take much less time hopefully).

@La0 please ping me when staging is un-broken again, so I can re-trigger an analysis.

**Comment by abpostelnicu** [comment]
There were sevaral issues why the bot only reported on mozilla checks:
1. the code was broken, it didn't compile so the generated ast was broken.
2. the logic behind the header filter was flawed, this was fixed here: https://hg.mozilla.org/mozilla-central/rev/5049afd1f26a

**Comment by La0** [comment]
@jankeromnes Staging is back up since monday afternoon.

**Comment by jankeromnes** [comment]
Great! Thanks. I have:

- updated the `staging` branch to latest `master`
- restarted the staging-pulse-listener
- uploaded a rebased (on top of Andi's fix) "bad patch" to: https://phabricator-dev.allizom.org/D324
- which triggered this analysis task: https://tools.taskcluster.net/groups/dEVGF9o_TsyZDUmyMkcikg/

**Comment by jankeromnes** [comment]
And the results are in! We even have two reviews for the price of one on https://phabricator-dev.allizom.org/D324 (I suspect that `testing` is now also analyzing Phabricator-dev patches).

- [ ] the bot found 4/11 clang-tidy defects (33% success)
  - it missed `readability-else-after-return` in `js/src/jsapi.cpp`
  - it missed `clang-analyzer-security.FloatLoopCounter` in `js/src/jsapi.cpp`
  - it missed `clang-analyzer-security.insecureAPI.UncheckedReturn` in `js/src/jsapi.cpp`
  - it missed `misc-suspicious-semicolon` in `js/src/jsapi.cpp`
  - ~~it missed `modernize-redundant-void-arg` in `js/src/jsapi.cpp`~~ (`publish: no`)
  - it missed `clang-analyzer-deadcode.DeadStores` in `js/src/jsapi.cpp`
  - it missed `performance-faster-string-find` in `js/src/jsapi.cpp`
  - ~~it missed `performance-implicit-conversion-in-loop` in `js/src/jsapi.cpp`~~ (not in clang-tidy 5.0 but in 6.0)
- [ ] the bot found 7/8 mozlint defects (88% success)
  - it missed `eslint: strict` in `devtools/client/menus.js`, but a local `./mach lint` finds it
  - ~~it missed `codespell: destributed` in `js/ductwork/debugger/JSDebugger.cpp`~~ (a local `codespell` doesn't find it either for some reason)

**Comment by jankeromnes** [comment]
When running `./mach static-analysis check` locally, I do find the missing issues. However, the bot doesn't even seem to detect them (they don't appear in the logs or in the email report). Maybe another output parsing issue? It would be great to see the raw `clang-tidy` output.

Additionally, the `eslint: strict` defect in `devtools/client/menus.js` *was* detected by the bot, but for some reason the bot considers it `Publishable: no` (see email report):

```
mozlint - eslint
    Path: devtools/client/menus.js
    Level: error
    Line: 31
    Third Party: no
    Disabled rule: no
    Publishable: no
    Is new: no

Use the global form of 'use strict'.
```

**Comment by jankeromnes** [comment]
Update: The missing `clang-tidy` defects don't seem to be a parsing issue, as revealed by dumping raw `clang-tidy` outputs. I filed issue #1256 about this, and may have found a relevant difference between the in-services and out-of-services run logs.

**Comment by jankeromnes** [comment]
Looks like @La0 was able to fix all undetected `clang-tidy` defects by adding the right dependencies to our Nix env!

With that, the `eslint: strict` remains the last issue to fix in order to fully validate analysis and enable Phabricator in production.

What's weird is that `lint.py` says [A mozlint issues is publishable when: * file is not 3rd party * rule is not disabled](https://github.com/mozilla-releng/services/blob/d62c7b3e678ce8aa052229c875df81a2a1ee17df/src/shipit_static_analysis/shipit_static_analysis/lint.py#L81-L87). In the email report, we can see that the `eslint: strict` defect is neither `Third party` nor `Disabled rule`, yet it still shows `Publishable: no`.

**Comment by jankeromnes** [comment]
Aha, the analysis' [report.json](https://taskcluster-artifacts.net/dEVGF9o_TsyZDUmyMkcikg/0/public/results/report.json) indicates that the `eslint: strict` issue is not `in_patch`, which is true because it's reported on the first code line *after* the commented-out `"use strict"`, but that line was not modified by the patch.

Hopefully this will be fixed with `BEFORE_AFTER` soon, but we don't need to block our Phabricator release on it.

**Comment by jankeromnes** [comment]
The fix from #1258 was deployed to `staging`, and I've sent another bad patch to [D324](https://phabricator-dev.allizom.org/D324).

Analysis is running: https://tools.taskcluster.net/groups/E3LiY0W6Q72GNJgUdrrX_w/

**Comment by jankeromnes** [comment]
10/10 clang-tidy defects, 7/7 mozlint defects, 100% success! https://irccloud.mozilla.com/pastebin/goicWMJC/defects.txt

**Comment by jankeromnes** [comment]
New staging analysis, just in case: https://tools.taskcluster.net/groups/Hpi4TqYKQJaGqugH6yvIgQ

**Comment by jankeromnes** [comment]
Update: I've now enabled automated Phabricator reviews in production, and reviews look good!

https://phabricator.services.mozilla.com/D2066

However, both MozReview and Phabricator reviews are currently broken for patches that touch C/C++ files (because of #1263). Once that issue is fixed, we should also validate that `clang-tidy` comments still look good.

Additionally, I've had to disable `clang-format` globally in production (also in debug email reports), because the Phabricator reporter doesn't have a filter yet like MozReview. I've filed issue #1264 to address this.

**Comment by jankeromnes** [comment]
10/10 and 7/7 on staging again! https://tools.taskcluster.net/groups/ZnCYTYy2QIqzyDnNHPiqWw/

This confirms that #1263's fix worked, and we can deploy it to production.

Additionally, we can see the analyzer raw dumps in the tasks artifacts, which is great (except `clang-format.txt`, maybe because `clang-format` is currently disabled on staging, although we do have a `clang-format.diff`).

**Comment by jankeromnes** [comment]
While waiting for general release next week, I'm trying to deploy a hot-fix for the Rust issue.

I've deployed the hot-fix to staging, and re-validated the bot: https://phabricator-dev.allizom.org/D541

Results: 4/10 expected `clang-tidy` defects and 7/7 expected `mozlint` defects.

**Comment by jankeromnes** [comment]
I've deployed a hot-fix to shipit-static-analysis-production with 2 fixes from master, and:

10/10 7/7 in production! 🎉🎉🎉 https://phabricator.services.mozilla.com/D2120

(And deploying on Friday the 13th wasn't so bad... 😝)

**Comment by jankeromnes** [comment]
I've tried validating MozReview the same way, but the analysis task failed with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 58204297: invalid start byte`:

https://tools.taskcluster.net/groups/Lp8DSs3xTHKPou13q85gUA/

I'll try to reproduce this bug locally and then bisect it.

**Comment by jankeromnes** [comment]
Hm, locally it worked: Production validated 10/10 7/7 on MozReview as well: https://reviewboard.mozilla.org/r/257216/#review264084

That intermittent `UnicodeDecodeError` is worrisome though, we should keep an eye on it.

**Comment by jankeromnes** [comment]
`reviewbot` was enabled on Phabricator last Friday, and it works great! :tada:
