### ISSUE TITLE
Missing flake8 issues which should be reported aren't

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/services#1192]
Here:
https://reviewboard.mozilla.org/r/247290/
I don't have any report of issue.

But locally with
` ./mach lint -l flake8`
or with treeherder:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=e5b7ee72b80dd4a5bc7ac9ffa91905178d3dc1e8&selectedJob=180700867
I can see a bunch of defects
 

> TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/js/src/devtools/gc/gc-test.py:11:1 | 'from subprocess import *' used; unable to detect undefined names (F403)
> TEST-UNEXPECTED-ERROR | /builds/worker/checkouts/gecko/js/src/devtools/gc/gc-test.py:60:9 | 'Popen' may be undefined, or defined from star imports: subprocess (F405)
> ...
>

**Comment by marco-c** [comment]
We're still using the old `in_patch` mechanism for now, so those issues are ignored as they are outside the patch.

**Comment by sylvestre** [comment]
I should not have an email with the correct information with the new mechanism?

**Comment by marco-c** [comment]
IIRC we either use one or the other, but @La0 can confirm.

**Comment by La0** [comment]
Current deployments:
* before/after on staging => only admin emails are sent
* in_patch on production => mozreview + admin emails

We should all have received some emails about this review, but i don't have anything related.
There is no trace in papertrail either... so the task was not started, or crashed early ?

I'll try to reproduce this locally

**Comment by sylvestre** [comment]
From IRC with bastien:
https://github.com/mozilla-releng/services/blob/master/src/shipit_static_analysis/shipit_static_analysis/lint.py#L162

**Comment by La0** [comment]
After local tests, mozlint does not find any issue here. This is a bug on our side

**Comment by sylvestre** [comment]
Fixed indeed:
https://reviewboard.mozilla.org/r/247290/#review254362
merci beaucoup!
