### ISSUE TITLE
shipit_pulse_listener is currently broken because of changes with scopes

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1249]
triggerHook is failing for missing scopes.

CC @garbas

**Comment by La0** [comment]
Both staging and production instances are running fine right now.
@marco-c Where did you encounter the errors ? Some chanegs were applied to Taskcluster scopes on Friday, that may induce this kind of errors.

**Comment by marco-c** [comment]
I received an email that my pulse queue was getting full, so I went on Heroku and saw the pulse listener wasn't running on staging. I restarted it and the exceptions about missing scopes were thrown, making the pulse listener stop again.

**Comment by marco-c** [comment]
> Both staging and production instances are running fine right now.

The pulse listener on staging is still not working.

**Comment by La0** [comment]
Just checked, pulse listener is down on staging (hence static analysis too). Looks like all these issues are related (tc scopes)

**Comment by garbas** [comment]
just fixed this. this was only affecting staging hooks that required `queue:create-task:aws-provisioner-v1/releng-task` scope, which was missing when jonas reorganized our roles/scopes to remove cycling dependencies.

i'm closing this, but please reopen if you see this issue is still occurring.

**Comment by marco-c** [comment]
Yes, it appears to be working now. The staging pulse listener is triggering a lot of tasks.
