### ISSUE TITLE
shipit_static_analysis: Parsing problem with clang-tidy issues

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#1251]
**Phabricator URL:** https://phabricator-dev.allizom.org/D324 (staging)

**Problem:** Some posted issues seem to include unrelated content in their body, e.g. in this issue:

```
Error: Methods annotated with moz_no_dangling_on_temporaries must return a pointer [clang-tidy: mozilla-dangling-on-temporary]

MOZ_NO_DANGLING_ON_TEMPORARIES int test() { return 0; } // mozilla-dangling-on-temporary
                                   ^

Warning: modernize-redundant-void-arg in /cache/sa-central/js/src/jsapi.cpp: redundant void argument list in function definition
```

the bottom part about "modernize-redundant-void-arg" is unrelated to the actual issue.

**Comment by jankeromnes** [comment]
Note: The email report called `[staging] New Static Analysis Phabricator #686 - PHID-DIFF-ocahda37wlvf4mcnyt7n` contains several examples of issues that have an unrelated "Warning" in their body.

**Comment by jankeromnes** [comment]
If you search for `cache/sa-central` in the email reports, you'll find plenty of occurrences of this parsing problem.

I wasn't able to find an occurrence in an existing review (on MozReview), because most of the occurrences I find are from `clang-format` issues, which aren't published.

**Comment by La0** [comment]
Here is the [raw output](https://pastebin.mozilla.org/9089036) of `./mach static-analysis check` on the diff **PHID-DIFF-ocahda37wlvf4mcnyt7n**

The bottom part is indeed unrelated to the error reported, this seems to be a repetition provided by clang-tidy for warnings (they are always present before the full line with `file:line:char`.

I guess i can skip those lines while searching for the errors body
