### ISSUE TITLE
shipit-static-analysis: clang-tidy doesn't detect some defects

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#1256]
When running inside `reviewbot` environment, a `clang-tidy` analysis detects fewer defects than when run locally in a `mozilla-central` clone.

Here is a run from a `reviewbot` environment (run via `please shell` in a clone of this repository, on an Ubuntu 16.04 server):

https://irccloud.mozilla.com/pastebin/30SSn6g9/clang-tidy-services.txt

And here is almost exactly the same command, but run inside a regular `mozilla-central` clone:

https://irccloud.mozilla.com/pastebin/EEQxsZT3/clang-tidy-janitor.txt

As you can see, the first run finds fewer defects as the second run (for example, try searching for `performance-faster-string-find`, which is only detected in the second run).

The only significant difference I can see between the two logs is:

```
/app/tmp/sa-central/obj-x86_64-pc-linux-gnu/dist/system_wrappers/new:3:15: error: 'new' file not found [clang-diagnostic-error]
```

Maybe this can be the root cause of this problem?

**Comment by jankeromnes** [comment]
Note: Both the `reviewbot` environment (`/tmp/mozilla-state/clang-tools/clang/bin/clang-tidy --version`) and my `mozilla-central` clone (`~/.mozbuild/clang-tools/clang/bin/clang-tidy --version`) use the same version of `clang-tidy`:

```
LLVM (http://llvm.org/):
  LLVM version 5.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell
```

**Comment by marco-c** [comment]
Another missing file is cstddef. I tried to find it in the docker image for static analysis:
```
./nix/store/bm7pb1s7rx1ad80706b5xqrznq7fgpgx-gcc-7.3.0/include/c++/7.3.0/cstddef
./nix/store/d1prcspbh2qsviipvnaxizcj8l3g7fpw-bootstrap-tools/include/c++/5.3.0/cstddef
```

Maybe we should force using gcc 6 instead of gcc 7 (gcc 6 is what we are currently using on CI for mozilla-central)?

**Comment by abpostelnicu** [comment]
yes we should try and do that, otherwise may be a difference in the environment itself.

**Comment by abpostelnicu** [comment]
I think all of the stdc++ headers should be somewhere in /usr/include/c++

**Comment by marco-c** [comment]
> I think all of the stdc++ headers should be somewhere in /usr/include/c++

The path is like that because it's Nix. I don't see the path in these env variables though: https://github.com/mozilla-releng/services/blob/master/nix/gecko_env.nix#L25. I'm not sure if the compiler is supposed to find it automatically.

I'm attaching the generated gecko-env from shipit-static-analysis. 
[gecko_env.log](https://github.com/mozilla-releng/services/files/2163939/gecko_env.log)

**Comment by abpostelnicu** [comment]
True, I’m wondering if mach build works in our environment.

**Comment by La0** [comment]
Yes i'm planning to work on it this afternoon, once the release is done.

**Comment by La0** [comment]
@abpostelnicu @marco-c [Here is the source code](https://github.com/mozilla-releng/services/blob/master/nix/gecko_env.nix#L24) generating the environment used by `./mach` in services

I think it's readable even without any Nix knowledge, as it only populates some environment variables.
Note that we are using clang as `CC` and `CXX` (not gcc).

I'm trying to reproduce in a simple test the bug around missing libraries, and will try to add some ni libs paths to the include paths.

**Comment by marco-c** [comment]
> @abpostelnicu @marco-c Here is the source code generating the environment used by ./mach in services

> I think it's readable even without any Nix knowledge, as it only populates some environment variables.
Note that we are using clang as CC and CXX (not gcc).

Yes, I've posted the generated output in https://github.com/mozilla-releng/services/issues/1256#issuecomment-402529122. Clearly the stdcpp path is missing, but I don't know if the compiler is supposed to find it automatically.

**Comment by abpostelnicu** [comment]
Strangely when we were using a locally build version of clang-tidy we didn’t have these kind of errors, right?

**Comment by abpostelnicu** [comment]
We shouldn’t have clang-diagnostic-error because this that starting with a specific node the ast gets broken so we cannot rely of the results.

**Comment by La0** [comment]
Good to know, because we have [been silently ignoring them for a long while](https://github.com/mozilla-releng/services/issues/391)

**Comment by La0** [comment]
I've created a script to quickly reproduce this issue in a nix shell, just [drop this file](https://gist.github.com/La0/4dd8e6fcfc7f015a4589bb438925bcaa) into your local clone tmp dir, and then:

```shell
./please shell shipit-static-analysis

# at least once to setup
/app/tmp/test_1256.sh 

# to avoid hg cloning over & over
/app/tmp/test_1256.sh fast
```

**Comment by La0** [comment]
The PR #1258 has been [deployed to staging](https://tools.taskcluster.net/groups/X6lJil-1SDeq7_MLjw7sMQ)
