### ISSUE TITLE
shipit-static-analysis: Update Rust to the version used on mozilla-central

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#1263]
Yet another case where the config mismatch bites us :(

https://hg.mozilla.org/integration/autoland/rev/f4f6234d143c

1.27.0 is the minimum required version now. We're using 1.28 beta on mozilla-central.

**Comment by abpostelnicu** [comment]
We should really consider moving to try.

**Comment by La0** [comment]
@abpostelnicu Yes but that will not happen right now. Do you know how i could track such changes on mozilla-central ? Is there a specific mailing list ?

Ideally i would need to be somehow notified when the Rust version needed changes, as this is the only one breaking regularly.

**Comment by marco-c** [comment]
We could parse the taskcluster yaml files at taskcluster/ci/toolchain/linux.yml and taskcluster/ci/build/linux.yml to see what mozilla-central is using.

**Comment by abpostelnicu** [comment]
What if we do our on extra bootstrap and each time before configuring the build we do things like: rustup?

**Comment by marco-c** [comment]
> What if we do our on extra bootstrap and each time before configuring the build we do things like: rustup?

The problem is that mozilla-central doesn't always use the latest Rust. For example we've used 1.24 for a long time, as there was some regression when switching to 1.25.

> I also wonder if we could get from artifacts rust....

We could, it is a toolchain build.

**Comment by abpostelnicu** [comment]
It seems there are targets for rust in toolchain: https://dxr.mozilla.org/mozilla-central/source/taskcluster/ci/toolchain/linux.yml#453

But I don’t see a proxy package.

**Comment by marco-c** [comment]
Here's an example: https://treeherder.mozilla.org/#/jobs?repo=try&revision=1a4ac2c635335490fe8bdd9faa0cf8860f1dada9&filter-searchStr=rust&selectedJob=184578715. Rust is in the rustc.tar.xz artifact of this task.
