### ISSUE TITLE
shipit-static-analysis: Phabricator review URL in email report doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#1269]
For Phabricator reviews, our email reports include URLs like this:

```
Review Url: https://phabricator.services.mozilla.com/PHID-DIFF-fmojuchlgczdbksfkbhx/
```

This URL doesn't work, because instead of the `diffPHID`, we should have a `revisionID` like `D2135`.

To get a Revision ID from the Diff PHID, we can do the following:
- Use the Conduit API [differential.diff.search](https://phabricator.services.mozilla.com/conduit/method/differential.diff.search/) with constraints = `{"phids":["${diffPHID}"]}` to find the `fields.revisionPHID` of the Diff
- Then use the Conduit API [differential.revision.search](https://phabricator.services.mozilla.com/conduit/method/differential.revision.search/) with constraints = `{"phids":["${revisionPHID}"]}` to find the `id` of the Revision
- The correct URL will then be `https://phabricator.services.mozilla.com/D${revisionID}`

**Comment by La0** [comment]
I already [fixed this issue](https://github.com/mozilla-releng/services/blob/master/src/shipit_static_analysis/shipit_static_analysis/revisions.py#L127) in 649c374a, but it's not on production yet.

**Comment by jankeromnes** [comment]
Amazing! Thanks, I'll mark this as resolved then.
