### ISSUE TITLE
Display deployed version of app on web page

### ISSUE THREAD

**Issue by hwine** [mozilla-releng/services#147]
E.g. at the bottom of every repository display page on hg.m.o, you'll find:
  ``Deployed from be8b3c0c996c at 2017-01-12T00:36:55Z.``
For rapid deployment systems, this is very helpful.

**Comment by garbas** [comment]
At the bottom, there is a link which points to tag and release notes. The timestamp of a tag is actually also the deployment date.

I don't think there is something to be done here.
