### ISSUE TITLE
Check list for Shipit dashboard in production

### ISSUE THREAD

**Issue by La0** [mozilla-releng/services#165]
Here are the steps to put Shipit dashboard in production

- [ ] Make a new release, update production tag.
- [ ] Check the Taskcluster building task is "all green".
- [ ] Check the papertrail logs of shipit_dashboard production to confirm all database migrations were successfull (no error messages after first gunicorn boot)
- [ ] Check the backend replies to a simple non-authenticated request : https://dashboard.shipit.mozilla-releng.net/ping should reply "pong"
- [ ] A new hook should be created for shipit_bot_uplift (i cannot confirm the setup is working for this, i used `make taskcluster-hooks-manual` to create https://tools.taskcluster.net/hooks/#project-shipit/services-staging-shipit_bot_uplift-bot
- [ ] If the hook is created check that it runs successfully (it should take ~ 20 mins on first run)
- [ ] Check the dashboard displays some bugs analysis on https://shipit.mozilla-releng.net/release-dashboard/2

As i don't think you have the TC scopes for using the dashboard, we may need to do the last checks together.

**Comment by garbas** [comment]
old issue closing
