### ISSUE TITLE
replace "Makefile" with something better

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#190]
- name it "mach" ask if it is understood what it does, maybe something else?
- use [click](https://pypi.python.org/pypi/click) to create command line interface
- a script needs to be bootstrappable without any (or very minimal) help from system libraries

**Comment by mozbhearsum** [comment]
I think it's probably better not to name it "mach", as that will probably end up being confused with Gecko's "mach".

**Comment by garbas** [comment]
I guess finding the name will be the hardest :)

So a shower and a coffee of thinking how to call it I'm really liking ``./please``. Why?
 - We can be super nice
 - We can have commands like: ``./please run shipit``, ``./please help-me-with shipit``

Anybody else has some suggestions (please also write a bit of reasoning why)?

**Comment by hwine** [comment]
Why are we creating yet another make alternative? (It would be helpful to know the business drivers.)

If 'make' doesn't work for us, what about gulp or SCons or ...?

What's the scope of this? Just dev & building? I.e. is the example ```./please run shipit``` in a dev context, or also for production deploy?

**Comment by garbas** [comment]
@hwine sorry this ticket is confusing and lack context. let me add some more context

(1) Currently, we are using make just to group few command together. eg: ``make develop APP=releng_treestatus`` runs 3 commands. It wouldn't be very hard to create command line utility which runs 3 other commands in order in python

(2) While I don't mind writing documentation I consider not needing a documentation to start using ``mozilla-releng/services`` even better solution.

(3) There is a plan to use ``coockicutter`` to have templates for different projects, #191. This would be trivial to do if our "main CLI" is already written in python.

So idea is to not write our own "make alternative" or any other tool, but to provide better command line experience.

**Comment by hwine** [comment]
Okay, in that context, it's a lot less open ended. One option to consider, if you're looking for "0 docs" is to make it follow traditional build conventions. E.g. one script with several entry points:
  - ./configure <= initial setup & template installation
  - ./build <= daily workhorse
  - ./intall <= dev install or link to deployment

Are you planning to require click to be installed already? Or will you vendor it into this project?
