### ISSUE TITLE
[uplift simulation] Should not simulate the uplift when not available in m-c

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/services#202]
When a patch is not in m-c, we should not try to simulate as it will fail.

Two cases:
1) A patch is for beta only:
```
Bug 1342095 - Uplift to beta

    Merge failed for commit 8840462 (parent 61519976b35f)
    abort: unknown revision '8840462'!
```
=> we should not even try

1) The uplift has been requested before the patch landed in mozilla-central 
```
Bug 1337826 - Uplift to aurora

    Merge failed for commit 8837260 (parent c9aca0047c81)
    abort: unknown revision '8837260'!
```
=> we should wait that it is in m-c

**Comment by garbas** [comment]
fixed in #210
