### ISSUE TITLE
"Upgrade week" (6.3. - 10.3)

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#209]
To not fall behind frameworks/libraries that we are using we need to spend a little time updating our code. 

## 1. Update

- [x] nixpkgs to latest channel, 2252465cfd2bf101820c2b17880b5598976332b0 (``nix-shell nix/update.nix --argstr pkg pkgs``)
- [x] update apps (@garbas)
  - releng_archiver (https://github.com/mozilla-releng/services/commit/6eaa4fe5703c1790fe5daf98eee490b1d2473500)
  - releng_clobberer (https://github.com/mozilla-releng/services/commit/729d0a18b87d16161aeb38df5dfdfc09bc9b888c)
  - releng_docs (https://github.com/mozilla-releng/services/commit/acfa82b1ca3501d9c0e813bf2e37b8c783923c2c)
  - releng_mapper (https://github.com/mozilla-releng/services/commit/eb60555d86ada992b13d1b35a6ada10bbc49498d)
  - releng_tooltool (https://github.com/mozilla-releng/services/commit/cd5a03cc4ebc5a6e949b522c33dc3790e1aa411c)
  - releng_treestatus (https://github.com/mozilla-releng/services/commit/688754d45cefe4d305796f06cb936431d35f02dc)
  - shipit_bot_uplift (https://github.com/mozilla-releng/services/commit/b0a41232b65c4851e69236b3299d8edf3f2ed0a9)
  - shipit_dashboard (https://github.com/mozilla-releng/services/commit/6b85779a5c5bb0f4b40d274ce23ce018cf595047)
  - shipit_pipeline (https://github.com/mozilla-releng/services/commit/a12ad8ad8731f839a929e8b7dc0eb06e462e9cab)
  - shipit_signoff (https://github.com/mozilla-releng/services/commit/8657c7336f62614487a01ce2ecd4a4c4d62eebc9)
- [x] update tools (@garbas)
  - pypi2nix -> ``make update-tool build-tool TOOL=pypi2nix`` (6b1ea17a19d17de463f8700c2b14566b1784f8c4)
  - awcli -> ``make update-tool build-tool TOOL=awscli`` (bf53ee49ddd6eab0e01b313e9ae9ad9fba21ec7e)
  - taskcluster-hooks -> ``make update-tool build-tool TOOL=taskcluster-hooks`` (68c1c22d3a5583f62f68014b3e4443187eee3425)
  - mysql2pgsql -> ``make update-tool build-tool TOOL=mysql2pgsql`` (fd318bcc473a05540dcede0f2d90f3588502f603)
  - node2nix -> ``make update-tool build-tool TOOL=node2nix`` (7472d7f2de3026dd920ab4936da43d39b7a86c2a)
  - push -> ``make update-tool build-tool TOOL=push`` (29250e133e2f9d0736f7cb0642be5eefd7fc9383)
- [x] update fronend apps (@La0)
- [x] Elm to 0.18 (@La0)
- [x] to latest bootstrap (@garbas)
- [x] to latest connextion (@La0)

## 2. Taskcluster

- [ ] replace current taskcluster tasks with one decision tasks which create only tasks which are needed.
- [ ] create a hook to trigger automatic updates on daily (apps) and weekly (nixpkgs / tools) basis.

## 3. Refractoring

- [x] rename ``shipit_dashboard`` to ``shipit_uplift``
- [x] create ``cli_common``, ``backend_common``, ``frontend_common`` from current code in ``lib/``
- [ ] deploy nixos to aws with configured nginx to handle additional security headers

**Comment by La0** [comment]
:warning: An sql query has to be run on staging & production database **before** restarting the heroku dyno for `shipit_uplift`:

```sql
alter table shipit_dashboard_alembic_version rename to shipit_uplift_alembic_version;
```
If it does not get run, the migration system tries to build the database from scratch.
