### ISSUE TITLE
Purge usage of sqlite

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#215]
According to @garbas:
> 16:11 < garbas> bhearsum: sqlite == old stuff, i dont think any application uses it, but there might be still some traces. please create an issue or just remove it :)

I think we'll need to replace at least some sqlite usage with postgres though? Eg: releng_mapper and shipit_pipeline (and maybe others) appears to require a database, and currently depend on sqlite in the Makefile.

**Comment by La0** [comment]
:+1: sqlite is a bad idea: we got some issues during the first deployments on heroku that would have been easily avoided if Postgresql was used since day one.
