### ISSUE TITLE
Docs should live beside the apps

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#230]
Currently, all of the functional parts of each app are isolated in src/{app} directories. We should put the docs in the same place - it helps maintain isolation between the apps, and seeing a "docs" directory in each will help us to remember to update them when we update the code.

**Comment by garbas** [comment]
@mozbhearsum would it be too dirty if we create a symlink from ``src/{app}/docs`` to ``src/releng_docs/{app}.

**Comment by mozbhearsum** [comment]
It's better than the current state, but it may have its own drawbacks. Eg: it probably won't work on Windows, and it blurs the line between apps a little bit.

**Comment by mozbhearsum** [comment]
If we do use smylinks, I actually think it would be better to go the other way too (having the real files live in src/{app}. This gives the benefit of everything to do with an app living within its directory, which makes "git log" and other tools work better.

**Comment by garbas** [comment]
:+1:

**Comment by mozbhearsum** [comment]
We created a model for doing this in #252.
