### ISSUE TITLE
Docs not updating?

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#251]
I don't see the recent changes to the Ship It docs on https://docs.mozilla-releng.net/services_releng.html or https://docs.staging.mozilla-releng.net/services_shipit.html.

**Comment by garbas** [comment]
https://docs.mozilla-releng.net/contributing.html#branching-policy

A rare thing that is documented :) If you have any idea how to make this more "visible" it would be awesome.

Changes will be visible with this week's release (Wed/Thu). Currently, we have a policy with Bastien that when he needs to have a release he pings me. Now that we are more people working on services repository it would make sense to make the release process more transparent and predictive.

Can we change this ticket to "Update docs on release process" and assign it to me?

**Comment by mozbhearsum** [comment]
Even after the latest release https://docs.mozilla-releng.net/services_shipit.html is not showing the step API from https://github.com/mozilla-releng/services/blob/master/src/releng_docs/services_shipit.rst.

**Comment by garbas** [comment]
@mozbhearsum you are right. looks like I remove - by accident - taskcluster github tasks for ``releng-docs``. I squeezed them inside #256
