### ISSUE TITLE
shipit_static_analysis: Post issues as drive-by reviews to MozReview

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#364]
I had a very useful chat with @smacleod yesterday, and we figured out what needs to be done in order to post our static analysis issues as actual MozReview comments:

- [x] We need to install ReviewBoard's `rbtools` packages, and copy/import the [batchreview.py](https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/mozreviewpulse/mozreviewpulse/batchreview.py) file (PR #400).
- [x] Create a Bugzilla account for our bot, then log in to ReviewBoard with it, and generate full-privileged Bugzilla API key (to store as a TaskCluster secret)
- [x] Create an `RBClient` API client from `rbtools.api` (with params like reviewboard_url, bz_user, bz_apikey) as in [this example code](https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/pylib/reviewboardmods/reviewboardmods/pushhooks.py#l83)
- [x] Create an `api_root` with `rbc.get_root()`
- [x] For each revision, initialize a `BatchReview` with `api_root`, as in [this example code](https://hg.mozilla.org/hgcustom/version-control-tools/file/0acfc2c6fd8e/pylib/mozreviewbots/mozreviewbotlib/__init__.py#l256)
- [x] Use the methods `review.comment()` and `review.publish()` to report our code issues as in [this example code](https://hg.mozilla.org/hgcustom/version-control-tools/file/0acfc2c6fd8e/pylib/mozreviewbots/pylintbot/__main__.py#l151) but with `ship_it=false` (we don't want to r+ things automatically, just report code issues)

Open questions:
- We currently report all code issues within a file that was touched, regardless of which lines were actually touched in that file (e.g. if you fix a whitespace in a big c++ file, we'll report all issues within that file). Instead, we could filter out any code issue that's not on a line that was actually modified, or go fancy and do something like "this line you added has problem X, and there are 83 other occurences of this problem in this file (use `./mach static-analysis` to list them all)".

**Comment by jankeromnes** [comment]
First part implemented in 0ec13e6fd77394b64a0a7550f8cf7d97b097a000.

**Comment by jankeromnes** [comment]
I just created linked `clangbot` accounts on Bugzilla and ReviewBoard for part 2.

**Comment by jankeromnes** [comment]
Regarding the open question about false positives, @La0 suggested using a whitelist to post only the issues we know are definitely helpful.

I would suggest whitelisting the following code issue types:
- `modernize-loop-convert`
- `modernize-use-default`
- `modernize-raw-string-literal`
- `modernize-use-nullptr`
- `performance-faster-string-find`
- `performance-for-range-copy`
- `readability-else-after-return`
- `readability-misleading-indentation`
- `readability-redundant-control-flow`

(That's basically [all of our checkers](https://github.com/mozilla-releng/services/blob/6a33f95681d4651b8db98ff88c1b4dcfa8c92b69/src/shipit_static_analysis/shipit_static_analysis/workflow.py#L106-L119) minus `clang-analyzer-deadcode.DeadStores`, `modernize-use-auto` and `modernize-use-override`, because these checkers have a some false positives. Actually we should even disable some of these in the bot.)

Also, I think we should ignore any feedback about files that are listed in [ThirdPartyPaths.txt](https://hg.mozilla.org/mozilla-central/file/tip/tools/rewriting/ThirdPartyPaths.txt).

**Comment by La0** [comment]
These are the last bits needed before activating MozReview publication:

- Limit reporting to 30 issues, add a comment when > 30
- Add a [summary comment](https://github.com/mozilla-releng/services/issues/552#issuecomment-331880150) into the review explaining what this is about
- When there are no issues detected, post a review (still r?) with simply a positive comment
- Specify Taskcluster environment in emails (staging vs. production)

```
The static analysis bot didn't find any code issues in this patch. Good job!
```

**Comment by jankeromnes** [comment]
Resolved fixed! Thanks team 😄 (and especially @La0 who did all the work).
