### ISSUE TITLE
shipit_uplift: Cache code coverage results from coveralls

### ISSUE THREAD

**Issue by La0** [mozilla-releng/services#365]
We need to develop a new API endpoint on shipit-uplift, that uses code coverage data, and generates the same json as the current artifact.

- [ ] Move artifact generation code from shipit-code-coverage to a shipit-uplift endpoint
- [ ] Remove useless anonymous TC artifact endpoint in shipit-uplift
- [ ] Cache generated file on Heroku worker file system (may fail) and regenerate it upon new requests (after a time to live of 1 hour)
- [ ] The endpoint should support a POST action to regenerate the cached file

**Comment by marco-c** [comment]
We have done this.
