### ISSUE TITLE
Document where source for Heroku deployment is located

### ISSUE THREAD

**Issue by edmorley** [mozilla-releng/services#366]
I was trying to find out how/why bug 1370311 occurred, however there is no reference to the `Access-Control-Allow-Origin` header in this repo. 

TreeStatus' API appears to be on Heroku:
```
$ curl -sSfIL https://treestatus.mozilla-releng.net/trees/mozilla-central | grep Via
Via: 1.1 vegur
```

...but yet this repo doesn't contain a Procfile.

The only reference I can find is on:
https://docs.mozilla-releng.net/deploying.html

...where it links to:
https://dashboard.heroku.com/apps/releng-production-treestatus

...however GitHub integration hasn't been set up for that app, so there's no linked GitHub repo to follow.

Could:
1) The location of the Heroku repo be documented
2) That repo be linked to the Heroku app, so changelogs etc on the Heroku activity page work

Thanks :-)

**Comment by edmorley** [comment]
> there is no reference to the Access-Control-Allow-Origin header in this repo

I see now that you are using Flask-cors, but I'll leave debugging that part to bug 1370311.

**Comment by garbas** [comment]
@edmorley I'm sorry you had to read so incomplete documentation, but i'm slowly adding it as time allows. I'm already impressed you found the right Heroku app :)

I'm going to fix this ASAP, but I will try to quickly explain it here:

1. https://treestatus.mozilla-releng.net is deployed to [heroku](
https://dashboard.heroku.com/apps/releng-production-treestatus) as you already discovered
2. its source code is in [this folder](https://github.com/mozilla-releng/services/tree/master/src/releng_treestatus)
3. it is a [flask application](https://github.com/mozilla-releng/services/blob/master/src/releng_treestatus/releng_treestatus/flask.py#L33) and configuration of flask application is in [settings.py](https://github.com/mozilla-releng/services/blob/master/src/releng_treestatus/settings.py)
4. if you follow the code you will see that common code that we use between flask applications is in [lib/backend_common](https://github.com/mozilla-releng/services/tree/master/lib/backend_common/backend_common). There is a [cors extension](https://github.com/mozilla-releng/services/blob/master/lib/backend_common/backend_common/cors.py) which is looking for ``CORS_ORIGINS`` in flask configuration. To define multple you need to [separate them with space](https://github.com/mozilla-releng/services/blob/master/lib/backend_common/backend_common/cors.py#L17).
5. in ``settings.py`` we load configuration and secrets using ``cli_common.taskcluster.get_secrets`` method, which fetches (in staging/production) from taskcluster secrets service.
6. taskcluster secret id used for production is ``repo:github.com/mozilla-releng/services:branch:production``. if you have enough permission/scopes you will be able to see that ``CORS_ORIGIINS`` is defined for ``releng_treestatus``.

**Comment by garbas** [comment]
I've added ``https://treeherder.mozilla.org`` to ``CORS_ORIGINS`` and restarted releng treestatus heroku app. 

I can confirm that https://treeherder.mozilla.com is now working correctly.

@edmorley Please re-open if it is not working for you.

**Comment by edmorley** [comment]
Thank you for your detailed reply :-)

Ah so the Heroku app is deployed from this repo - digging more now I see you're using the container registry, hence not having a Procfile?

What's confusing is that the Heroku app's own `CORS_ORIGINS` environment variable is set to `*` still, eg see:
https://dashboard.heroku.com/apps/releng-production-treestatus/settings
...I'm presuming the app has now switched to using Taskcluster secrets instead of these environment variables? Could these stale variables be deleted from the Heroku app to reduce confusion?

> I've added https://treeherder.mozilla.org to CORS_ORIGINS and restarted releng treestatus heroku app.

Unfortuanately this doesn't help stage, prototype, local development environments etc. We really need the wildcard back please?

Also, if changing the `Access-Control-Allow-Origin` in the future it would be really useful to have emails sent to mailing lists and also grep access logs to see who consumes the API before breaking changes are made.

**Comment by edmorley** [comment]
Seeing as this issue is now discussing the CORS breakage, I'll morph the summary and file new issues for the OP.

**Comment by edmorley** [comment]
I've filed #367, #368, #369 to help ease future debugging.

In the meantime, would you mind reopening this issue, given the above?

**Comment by garbas** [comment]
@edmorley aaa damn, i see now. this is a regression, since it used to be set to ``*`` before. damn it. sorry i'm adding star back to CORS_ORIGINS.

And I really appreciate the tickets. I'm going to make sure I document this until next release (this Thursday).

**Comment by garbas** [comment]
Without reopening I changed ``CORS_ORIGINS`` back to ``*``. I blame this on Tuesday snicking on my and pretending to be Monday.

/me needs to find a way to warn people that I'm slow after long weekends

**Comment by edmorley** [comment]
Ah many thanks! I thought it might have been an intentional change to not use a wildcard, but I see not now.

Working great:
```
$ curl -sSfIL https://treestatus.mozilla-releng.net/trees/mozilla-central | grep Access
Access-Control-Allow-Origin: *
```
