### ISSUE TITLE
TryChooser no longer displays pending/running counts for platforms

### ISSUE THREAD

**Issue by Standard8** [mozilla-releng/services#385]
TryChooser used to have functionality that displayed pending/running counts for platforms broken down by builds & tests. At some stage this stopped working.

TryChooser is pinging:
https://builddata.pub.build.mozilla.org/reports/pending/pending_compile_try.txt
https://builddata.pub.build.mozilla.org/reports/pending/pending_test_all.txt

However, for both of those the cert is invalid (it is for secure.pub....). Even if you ignore the invalid cert, then it still fails as the reports return "forbidden".

It seems like we should either update the urls to new ones, or remove the functionality. Does anyone know if there's new urls currently? /cc @nthomas-mozilla maybe?

**Comment by nthomas-mozilla** [comment]
Those files were coming off a system which has been discontinued. see https://bugzilla.mozilla.org/show_bug.cgi?id=1260609 and 1264168. I'm don't know if we can get pending out of taskcluster, but that's the place to target these days. Assuming pending counts are still useful.

**Comment by Standard8** [comment]
Ok, I'm going to get a patch together to drop the pending counts. If someone complains, we can try and find another route.

**Comment by Standard8** [comment]
(tbh, the existing UI isn't great, so having a few less items on there would be good).

**Comment by garbas** [comment]
@Standard8 👍 

I wonder if it would make sense to spend a little more time on a rewrite of trychooser so that you dont really have to change code (and send PR) to be able to show more options. You would go to the "admin" part of the trychooser and add them with few clicks. I think that would save a lot of time across mozilla.

**Comment by Standard8** [comment]
@garbas Hmm, interesting idea. It certainly would be nice for some sort of dynamic config for loading possible build/test options. We'd probably still need a bit of backend for managing the logic, but I guess that wouldn't be too hard.

Maybe we could even hook it up to get the list of possibilities from the mach try chooser somehow (or however it does that).

Unfortunately it isn't a project I have time for, but it would certainly be interesting to be involved with.

Maybe we can get a discussion going on it somewhere if there's someone looking to rewrite it?
