### ISSUE TITLE
shipit_code_coverage: Trigger code coverage task when a linux64-ccov build is complete

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#404]
Instead of running the task daily, we should wait for a new linux64-ccov build to be complete and all its tests to be run.

**Comment by marco-c** [comment]
https://wiki.mozilla.org/Auto-tools/Projects/Pulse/Exchanges#Queue:_Task_Completed

**Comment by La0** [comment]
This will be done directly b yTreeherder

**Comment by marco-c** [comment]
I have a patch for this. We decided to switch to pulse again as running the hook from treeherder is a bit of a pain (at least until we have a way to trigger hooks with parameters).
