### ISSUE TITLE
"./please shell" reinstalls packages every time i run it

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#430]
In Docker mode, it appears that a new container is created each time I run "./please shell". After running it a few times, I have a few containters running, each having installed their own set of packages:
```
➜  services git:(master) docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS               NAMES
8d5ab585fe34        mozillareleng/services:base-latest   "./please shell shipi"   55 seconds ago      Up 53 seconds                           peaceful_newton
a73883f09834        mozillareleng/services:base-latest   "./please shell shipi"   2 minutes ago       Up 2 minutes                            sick_fermat
5b085ff19cda        mozillareleng/services:base-latest   "./please shell shipi"   5 minutes ago       Up 5 minutes                            jovial_bartik
```

Probably it should name the container so the same one can be reused across multiple sessions.

**Comment by mozbhearsum** [comment]
Unfortunately, this + #457 means that I end up waiting multiple minutes each time I make a code change, making ./please more or less unusable at the moment :(.

**Comment by garbas** [comment]
this was fixed with current docker support since all commands run inside one docker container.
