### ISSUE TITLE
base_image should be using a non-root user (eg. app) 

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#432]
We need to setup [USER](https://docs.docker.com/engine/reference/builder/#user) in [Dockerfile template](https://github.com/mozilla-releng/services/blob/master/lib/please_cli/please_cli/base_image.py#L23)

---

Running as a non-root user is needed (among other things) to run PostgreSQL

PostgreSQL fails to start with `./please run postgresql`

Got this:
```
initdb: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
ERROR
    Show details? [y/N] 
```

I assume this is running in Docker mode, and I've run please as "bhearsum", so something appears to be going wrong within the container.

**Comment by mozbhearsum** [comment]
When I tried to get more details, it hung.

**Comment by garbas** [comment]
this  is also fixed with current docker support, all commands are run as ``app`` user.
