### ISSUE TITLE
static_analyzer: move the list of checkers into a configuration file

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/services#437]
For now, the list of checkers is here:
https://github.com/mozilla-releng/services/blob/6638ae6a7e68c4ea79bb4577b6d70516f6844fdd/src/shipit_static_analysis/shipit_static_analysis/workflow.py#L104
we should move that into a configuration file

**Comment by La0** [comment]
We actually use taskcluster secrets for configuration: would that work for you ?
If we move the checkers list in a TC secret, the list can be easily modified through a web interface + changes are picked up immediately.

**Comment by sylvestre** [comment]
Are TC secrets public or not?

**Comment by La0** [comment]
Nope.
As discussed, i'll use a config file in the repo to list all the checkers.

**Comment by La0** [comment]
Merged.
