### ISSUE TITLE
shipit_static_analysis: We should use Mozilla's clang-tidy instead of the upstream one

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#451]
This would allow our bot use use Mozilla-specific checkers on reviews.

In the future, we'll be able to simply use `./mach static-analysis`, but in the meantime, we can install a Mozilla-specific `clang-tidy` with the following command:

    ./mach artifact toolchain --from-build linux64-clang-tidy

After that we could use `./clang/bin/clang-tidy` to run our static analysis.

**Comment by La0** [comment]
I'm trying that today.

**Comment by La0** [comment]
Merged.
