### ISSUE TITLE
flask apps should autoreload on code change

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/services#457]
Currently, I need to manually restart the app to pick up any changes to the code. This is annoying, and slows me down. Flask has the ability to autoreload on code change - we should use it!

**Comment by mozbhearsum** [comment]
I haven't figured out how to do this with please/gunicorn, but when running on my host system with "flask run", I just need to pass "--reload" to it.

**Comment by cgsheeh** [comment]
@mozbhearsum using ./please with Nix, the Python code does autoreload on saving a change. Maybe this is a Docker related issue?

**Comment by mozbhearsum** [comment]
I've actually been running "flask run" directly (on my host machine) so far, so I'm not actually sure what happens in Docker. If it works with please + nix, it will probably work with please + docker, though.

**Comment by garbas** [comment]
I have just tested this and it works inside container.
