### ISSUE TITLE
Load one directory at a time

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#508]
The backend is currently generating the entire report on demand and caching it (as it's really big and takes a lot of time to generate).
We could make the backend generate one directory at a time.

**Comment by garbas** [comment]
There is cache extention in backend_common, and is already being set in heroku.

All you need to is use a decorator.

_Sent from my Samsung SM-A520F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by garbas** [comment]
Example of usage
https://github.com/mozilla-releng/services/blob/master/src/releng_treestatus/releng_treestatus/api.py#L101

And this is how you configure it
https://github.com/mozilla-releng/services/blob/master/src/releng_treestatus/settings.py#L59
