### ISSUE TITLE
shipit_static_analysis: Limit exported MozReview issues to a small number

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#552]
If our bot finds more than (say) 30 issues inside a commit, it shouldn't post about all these issues (because MozReview's UI would get horribly slow).

Instead, we should truncate at (say) 30 issues, and then add a comment:

> You commit has too many problems (34567). We only report the first 30.
> Please fix your commit by running something like `./clang/share/clang/run-clang-tidy.py -clang-tidy-binary ./clang/bin/clang-tidy -p obj-x86_64-pc-linux-gnu/ -checks=-*,<checks> ./path/to/file.cpp -fix`.

**Comment by jankeromnes** [comment]
Note, such a "review summary comment" could be posted to MozReview using the [body_top](https://www.reviewboard.org/docs/manual/2.0/webapi/2.0/resources/review/#PUT) parameter.

It should probably include:
- Some basic info on what `clangbot` is, and why it is posting comments on this review request
- The number of code defects found (and a special mention if there were too many issues to post them all)
- A one-liner to allow the developer to check their patches locally before pushing again

**Comment by jankeromnes** [comment]
For example:

```
Static analysis found 55 code issues in this patch (only the first 30 are reported here). Please either fix them before landing it.

To run static analysis locally, please use: `./mach static-analysis check path/to/file.cpp`

If you notice a problem in this automated review, please [report it here](https://github.com/mozilla-releng/services/issues/new?title=shipit_static_analysis%3A%20Problem%20with%20a%20MozReview%20auto-review&body=**MozReview%20URL%3A**%20https%3A%2F%2Freviewboard.mozilla.org%2Fr%2F%E2%80%A6%0A%0A**Problem%3A**%20%E2%80%A6).
```

(Note: the `(only the first 30 are reported here)` part should only be included if there are > 30 issues.)

**Comment by sylvestre** [comment]
s/code issues/defect/ 
otherwise, sound good

**Comment by jankeromnes** [comment]
> s/code issues/defect/

Thanks! I chose "code issues" because some things aren't really defects, just valid code that can be modernized or improved some other way. But fair enough for defects!

**Comment by sylvestre** [comment]
right, as you wish then :)

**Comment by jankeromnes** [comment]
I believe that we now cap exported issues to 30. Thanks!
