### ISSUE TITLE
shipit_bot_uplift: the subject of the email should say which branches are impacted

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/services#582]
Currently, the subject of the email is

> Uplift bot detected some merge failures

We should have

> Uplift bot detected some merge failures to beta, esr52

**Comment by jankeromnes** [comment]
The email subject is formatted [here](https://github.com/mozilla-releng/services/blob/c8a91817c4ff0cf40556c3f861159754d150e7b0/src/shipit_bot_uplift/shipit_bot_uplift/report.py#L55-L58).

Below, you can see that the code iterates over branches that have failed merges. Maybe during that iteration, we could append `branch` to the email subject?

@sylvestre is this still a change you'd find valuable? If so, I'm happy to implement it.
