### ISSUE TITLE
shipit-uplift fails to start

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#584]
This is what I get:

> armenzg@armenzg-mbp services$ ./please run shipit-uplift
>  => Checking if database `services` exists ... DONE
>  => Running shipit-uplift on https://0.0.0.0:8011 ...
> 1+0 records in
> 1+0 records out
> 24 bytes copied, 3.73e-05 s, 643 kB/s
> [2017-08-30 18:21:29 +0000] [7337] [INFO] Starting gunicorn 19.7.1
> [2017-08-30 18:21:29 +0000] [7337] [INFO] Listening at: https://0.0.0.0:8011 (7337)
> ...

It gets stuck here and never ends:

> connexion.operation: ... Adding produces decorator (<function Operation.__content_type_decorator.<locals>.<lambda> at 0x7fef630e4ea0>)
> connexion.operation: ... Security: None
> connexion.operation: ... Adding security decorator (<function security_passthrough at 0x7fef6370f510>)

**Comment by armenzg** [comment]
Well it seems that it is actually working.
I was expecting a message saying that we're ready to go or even a link to localhost.

Once I loaded https://0.0.0.0:8011 I had to add a security exception.

I'm happy to close this. Let me know if there's anything you think that could have made my life easier.

**Comment by garbas** [comment]
I'm closing this since i don't have any idea how to improve this (any suggestions are welcome).
