### ISSUE TITLE
Timeout when looking at the coverage results

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/services#587]
On https://shipit.mozilla-releng.net/code-coverage/modules/brotli
I am getting:
`Error loading code coverage: NetworkError`

**Comment by marco-c** [comment]
This should be fixed with https://github.com/mozilla-releng/services/commit/7aec0fb83e2cca36db74176e952949736bff864c.

(Note the URL should contain `staging`: https://shipit.staging.mozilla-releng.net/code-coverage/modules/brotli).
