### ISSUE TITLE
Add Access-Control-Allow-Credentials for code coverage APIs

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#598]
FYI @marco-c  

We want to make them available to the world.

**Comment by armenzg** [comment]
Reference:
http://flask-cors.readthedocs.io/en/latest/
http://flask.pocoo.org/snippets/56/

**Comment by armenzg** [comment]
Please re-open if you believe there's anything else.

**Comment by marco-c** [comment]
Note the patch hasn't landed yet, so while this is in staging now it could be removed when someone creates a new release. I'll reopen it and close it again once the patch lands.
