### ISSUE TITLE
Intermittent CORS issue for shipit-uplift

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#611]
CC @marco-c 

Are there different web heads serving different versions of the APP?

I've got intermittent issues for both APIs: /coverage/{changeset,changeset_summary}

Fetch API cannot load https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset/ab06fc49527dbf1e1417c9a2fa2a99538ca69974. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

**Comment by marco-c** [comment]
Probably it was a heroku timeout

**Comment by marco-c** [comment]
Since we are caching things, a simple thing you could do is retry the request again. If it is failing because of a timeout, maybe the second time it will be successful.

If we run into timeouts too often, we can consider changing the API a bit to make it faster (or less prone to timeouts).
