### ISSUE TITLE
"Can't load codecov.io report"

### ISSUE THREAD

**Issue by armenzg** [mozilla-releng/services#620]
CC @marco-c 

If you load:
https://uplift.shipit.staging.mozilla-releng.net/coverage/changeset/850ec078a6adefce651d8c97c3db53fc91a02e34
you get:
"Can't load codecov.io report"

There's something that happened to this changeset:
https://codecov.io/gh/marco-c/gecko-dev/commit/cc8349a4a8428b0eeeea632df8ef42e68dfcb5bb

Other commits look fine.

**Comment by marco-c** [comment]
I don't know what happened there, but I've removed it from codecov. The issue should be fixed now.

**Comment by marco-c** [comment]
Now that I've removed it, the build right after cc8349a4a8428b0eeeea632df8ef42e68dfcb5bb (which is 65bd75b8f9a8d6b507138aa3a993ae608277b2ff) returns an emtpy value for `parent_totals`.
We have to handle this somehow, even though it should be pretty rare.
