### ISSUE TITLE
shipit_uplift: Use a worker to process coverage API requests

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#632]
This will avoid timeouts (such as #551).

**Comment by armenzg** [comment]
Not being able to query the APIs reliably is making developing the frontend very challenging.
I also don't have access to the logs of the backend and I hear it is all over multiple heads.

**Comment by marco-c** [comment]
> Not being able to query the APIs reliably is making developing the frontend very challenging.

The timeouts should be only limited to large changesets. Are you seeing them with smaller changesets too?

> I also don't have access to the logs of the backend and I hear it is all over multiple heads.

I don't know how to give you access, but I'll figure it out. Anyway, I can tell you that the requests which are timing out are timing out because they make a lot of requests to codecov.io.

**Comment by armenzg** [comment]
3/7 of the requests seem to have failed:
https://cl.ly/222l2q0v3A2Y

Should I wait a little longer before trying again?

**Comment by marco-c** [comment]
It hadn't been deployed yet, it is deployed now.
The requests will return 202 until they are finished, at that point they will return either 200 or an error.
