### ISSUE TITLE
shipit_static_analysis: Problem with an automated review [modernize-raw-string-literal]

### ISSUE THREAD

**Issue by squelart** [mozilla-releng/services#659]
**MozReview URL:** https://reviewboard.mozilla.org/r/174110/#review192124

**Problem:** Is this a warning we really want?

```
Warning: Escaped string literal can be written as a raw string literal [clang-tidy: modernize-raw-string-literal]

  void match(const char* a) const { mString.AppendPrintf("\"%s\"", a); }
                                                         ^
                                                         R"("%s")"
```

**Comment by jankeromnes** [comment]
Thanks for reporting this issue!

@sylvestre Any thoughts on this? I don't know how valuable raw string literals are, or whether we should disable this checker.

**Comment by sylvestre** [comment]
@squelart Do you see an issue with that? I find that the proposition is more readable than the initial, don't you think?

**Comment by jankeromnes** [comment]
To be fair, this is a quite small example, so maybe it doesn't make the checker's value very obvious.

Here are a few more examples of what this checker suggests:

      mViewSourceTitle.AssignLiteral("data:\xE2\x80\xA6");
                                     ^
                                     R"(data:…)"

    aOutput.AssignLiteral("<IMG src=\"data:");
                          ^
                          R"(<IMG src="data:)"

    aOutDescription.AppendLiteral("=\"");
                                  ^
                                  R"(=")"

I think it especially makes code snippets (like HTML, JS, regexes, ...) and unicode characters (like ellipsis and emdash) very readable. However, if you feel this rule shouldn't be enforced by our bot for all code, it would be fair to run the question by `dev-platform` and see how people weigh benefits vs annoyance of this checker.

**Comment by squelart** [comment]
I guess I was surprised with the sudden appearance of these static analysis result popping up after what I thought was my final push!
But I do see the value in these automated checks (thank you so much for working on them), and I see how some strings become more readable. I admit I have never used raw string literals, so this may be just what I needed to give them a go. :-)
So I think they should stay. Sorry for the noise.

**Comment by jankeromnes** [comment]
Thank you for reporting back! Your question was definitely worth asking, so it wasn't noise.

> I guess I was surprised with the sudden appearance of these static analysis result popping up after what I thought was my final push!

We only enabled `clangbot` recently, which explains why it only analyzed your latest push (sorry for intercepting it at the last minute!)

> But I do see the value in these automated checks (thank you so much for working on them), and I see how some strings become more readable.

You're very welcome! And thank you for giving them a try. :-)
