### ISSUE TITLE
shipit_static_analysis: Problem with an automated review ([modernize-raw-string-literal] suggestions missing PRI macros)

### ISSUE THREAD

**Issue by squelart** [mozilla-releng/services#662]
**MozReview URL:** https://reviewboard.mozilla.org/r/174110/#review192124

**Problem:** 
```
Warning: Escaped string literal can be written as a raw string literal [clang-tidy: modernize-raw-string-literal]
    mString.AppendPrintf("MediaResult(%s =0x%08" PRIx32 ", \"%s\")",
                         ^
                         R"(MediaResult(%s =0x%08x, "%s"))"
```
Notice that the original string contains `"%" PRIx32` corresponding to a uint32_t argument, but the suggestion has it changed to `"%x"`.

It is quite possible that this suggestion is technically equivalent at the moment (as uint32_t===unsigned on all our platforms), but will it always be?
And I think it loses the explicit & clearer format specification I chose.

Note: Issue #659 was for the same review URL and suggestions, but wondered if the whole [modernize-raw-string-literal] thing was useful (*spoiler alert* yes); this issue here is about a potentially-real problem with the given suggestions when the original code includes PRI macros.

**Comment by jankeromnes** [comment]
Thanks for reporting this issue! I guess this particular clangbot suggestion can be dropped for now, as it seems controversial.

@abpostelnicu any thoughts about this `clang-tidy` suggestion? Does it look like a risky false positive we should avoid?

**Comment by abpostelnicu** [comment]
I think this is safe because I don't think we target platform that target LP32 data models. As far as I remember only win16 api target LP32 model.

**Comment by La0** [comment]
@jankeromnes @abpostelnicu Can we close this issue ?

**Comment by abpostelnicu** [comment]
If @squelart agrees with what I've stated yes.

**Comment by squelart** [comment]
Though I agree that it is safe now, I still disagree with losing PRI macros as they are clearer in intent and more portable.
But if that would be too much work to prevent losing PRI macros, it wouldn't be too bad in the end, as we have printf-format checks in builds.

So I personally vote to keep this issue open, but I won't complain if the majority chooses to close it. In any case, thank you for considering it.

**Comment by jankeromnes** [comment]
> Though I agree that it is safe now, I still disagree with losing PRI macros as they are clearer in intent and more portable.

I agree with you here, and I think the fact that clang-tidy's suggestion is missing the `PRIx32` macro is due more to the fact that it works on fully expanded code than the macro being actually unnecessary.

As I'm not sure what the correct raw string literal with `PRIx32` macro would look like, please feel free to ignore and drop this particular MozReview issue.
