### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by Yoric** [mozilla-releng/services#671]
**MozReview URL:** https://reviewboard.mozilla.org/r/…

**Problem:** 

The following snippet is tagged as bad, because there is an `else` after a `return`:

```c++
if (foo)
  return 0;
else
  return 1;
```

However, this is one of the cases in which putting the `else` is clearer than not putting it. I believe that this case is a bit overzealous.

**Comment by jankeromnes** [comment]
Thanks for filing this issue! I agree that in your example, complaining about the `else` is a bit overzealous.

As any other false positive, please feel free to drop any such MozReview issue without addressing it. Or in this case, you could use a ternary expression (as I believe was your workaround). Sorry that our bot's feedback was a bit counter-productive for you.
