### ISSUE TITLE
shipit_static_analysis: Problem with an automated review when using gtest infrastructure

### ISSUE THREAD

**Issue by jyavenard** [mozilla-releng/services#674]
**MozReview URL:** https://reviewboard.mozilla.org/r/…

**Problem:** …
The code creates issues for existing code, and code that is from external framework.

Example:
https://reviewboard.mozilla.org/r/189112/#issue-summary

This prevents from writing gtest.

**Comment by jankeromnes** [comment]
Indeed, sorry for all the noise! Thank you for filing this issue, and please drop all these unhelpful MozReview comments.

As mentioned in our mailing list, this was originally reported as #658, and the fix should get to production some time tomorrow, after which our bot will stop complaining about these `TEST` macros.
