### ISSUE TITLE
Treestatus: Cannot close tree, "update" button isn't displayed

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/services#700]
Today is merge-day! I've been unable to close mozilla-beta. apavel who's on sheriffduty got some trouble as well, but eventually got to see the button. henrietta_maior said the issue is intermittent

What I did on my end was:

1. Go to https://mozilla-releng.net/treestatus/show/mozilla-beta
1. Log in and get redirected to the page above. See no button
1. Hard-refresh the page
1. Visit https://mozilla-releng.net/treestatus/update but get redirected to the main page.
1. From the main page, reach mozilla-beta. See no button still.
1. Log out and log back in again => No button.
1. From a clean Firefox profile, log in => No button.

I'm unsure what caused the issue, maybe the group I'm in isn't able to modify the tree anymore. What do you think @garbas ?

**Comment by garbas** [comment]
@JohanLorenzo I don't this is a problem with permission. everybody in releng group should have admin rights.

But I think there is a bug with fetching scopes from taskcluster which is responsible to show / hide buttons. Could you try to:

1. Go to https://mozilla-releng.net/treestatus/show/mozilla-beta
2. Log in and get redirected to the page above. See no button
3. Click on "RELEASE ENGINEERING" at top left
4. Then navigate back to TreeStatus. Buttons should be visible.

It looks like i "just" need to find the right place to load scopes.

**Comment by JohanLorenzo** [comment]
I'm sorry, that doesn't work on my end.

**Comment by garbas** [comment]
Closing this as fix just landed and was released.

**Comment by JohanLorenzo** [comment]
Thank you very much! I tested it again, and I now see the button.
