### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by staktrace** [mozilla-releng/services#707]
**MozReview URL:** https://reviewboard.mozilla.org/r/197236/#review202364

**Problem:** clangbot spew into the bug, even though it found 0 issues with the patches. I thought it wasn't supposed to say anything if it found 0 issues?

https://bugzilla.mozilla.org/show_bug.cgi?id=1415225#c6

**Comment by La0** [comment]
This looks like a bug in the latest version of the static-analysis bot.
I've disabled mozreview publication for now, and will work on a solution for this.

**Comment by staktrace** [comment]
I don't think the disabling worked, it's still spewing stuff, see https://bugzilla.mozilla.org/show_bug.cgi?id=1399692

**Comment by La0** [comment]
@staktrace It got restarted unfortunately 👎 
Now it's gone for good while we wait for the [deployment](https://tools.taskcluster.net/groups/brvSlpQsTlOrr6FcwNA0CQ)
