### ISSUE TITLE
[Question] Missing taskcluster in /etc/hosts

### ISSUE THREAD

**Issue by allan-silva** [mozilla-releng/services#723]
I'm restarted work at #601 and after have sync my branch with upstream, I got the following error:
`Exception: Missing taskcluster in /etc/hosts`

Should taskcluster configuration be inside docker container or in my host system `/etc/hosts"?

Some logs:
https://pastebin.mozilla.org/9073383
https://pastebin.mozilla.org/9073385

**Comment by garbas** [comment]
@allan-silva there were some changes how `./please run/shell` command works. it now needs to provide `--taskcluster-client-id` and ` --taskcluster-access-token`, but this is not true for all projects. Would it be ok if I rebase your PR on master? Also feel free to ping me on IRC to get your development environment and up and running asap.

**Comment by allan-silva** [comment]
Ok, thanks!
Actually my local branch is already rebased with upstream/master. I'll try clean up my env and try again.
