### ISSUE TITLE
shipit_static_analysis: Locking cache directory is unnecessary

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#749]
AFAICT, the cache volume is not shared between tasks that are running concurrently.

See the test at https://github.com/taskcluster/docker-worker/blob/c79bc7ca74000b57955e1763f88f60ec4b005ca0/test/integration/container_volume_caching_test.js#L119 for example.

**Comment by La0** [comment]
Didn't know about this, so we may remove LockDir for the next release
