### ISSUE TITLE
app.run_options() is not a valid method

### ISSUE THREAD

**Issue by rail** [mozilla-releng/services#75]
I tried to create an example app and failed to use the `app.run(**app.run_options())` pattern. Looks like the proper call is `app.run(**app.get_run_options())`

**Comment by garbas** [comment]
get_run_options is a custom method we create in ``releng_common``. where did you find the instructions to use ``run_options``?

**Comment by rail** [comment]
https://github.com/mozilla-releng/services/search?utf8=%E2%9C%93&q=run_options give me 3 entries:
https://github.com/mozilla-releng/services/blob/e5b8e78c930c3d95b5a86d353f375bf6573cd1a7/src/releng_tooltool/releng_tooltool/__init__.py#L41
https://github.com/mozilla-releng/services/blob/3cc0c8d4c6fa349c750e454e544d21abd647ddae/src/releng_clobberer/releng_clobberer/__init__.py#L50
https://github.com/mozilla-releng/services/blob/45b644eaa5c7bb7612cfe1f141ecc7148f384d44/src/shipit_dashboard/shipit_dashboard/__init__.py#L41

**Comment by garbas** [comment]
maybe we should rename ``get_run_options`` to ``run_options`` in releng_common? since if i understand correctly ``run_options`` is how bare flask would do it

**Comment by rail** [comment]
WFM :)

**Comment by garbas** [comment]
this got merged
