### ISSUE TITLE
Simplify labels

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#755]
The current format is:
NUMBER.TYPE: ACTUAL-LABEL

NUMBER is basically the same as the TYPE, as there's a 1:1 mapping between them.

I propose we drop "NUMBER." and only keep "TYPE: ACTUAL-LABEL" or "TYPE:ACTUAL-LABEL" (I don't like the space that turns into %20 in URLs :P)

CC @garbas

**Comment by marco-c** [comment]
Once we're done with this, we should add labels to specify programming languages (so that we show up correctly on [bugsahoy](https://www.joshmatthews.net/bugsahoy/)).

**Comment by garbas** [comment]
@marco-c i use number as a shortcut, but i'm ok to remove it.

for specification of programming languages i'd go with `skill:` but anything you choose i'm ok with. just a suggestion.

:+100: for getting things into bugsahoy

**Comment by marco-c** [comment]
> for specification of programming languages i'd go with skill: but anything you choose i'm ok with. just a suggestion.

I've used `lang` (e.g. `lang: python`).

I will simplify the labels as proposed, and I'll update bugsahoy with the new labels, then I'll close this.

**Comment by marco-c** [comment]
Done.
