### ISSUE TITLE
shipit_static_analysis: Tweak mozlint issue reporting

### ISSUE THREAD

**Issue by jankeromnes** [mozilla-releng/services#757]
We recently published an automated review including MOZLINT feedback (i.e. JS and Python linting): https://reviewboard.mozilla.org/r/184106/#review218568

I think we can improve the review comments our bot posts for MOZLINT issues. Here are some suggestions:

> > 7: const Services=require("Services"); // space-infix-ops (eslint)
> 
> Error: Linting issue [mozlint: eslint]
> 
> Infix operators must be spaced.

I think this would be clearer / more valuable like so:

```
Error: Infix operators must be spaced. [eslint: space-infix-ops]
```

---

> > 7: # Make this available to both AMD and CJS environments // Parsing error: Unexpected character '#'  (eslint)
> 
> Error: Linting issue [mozlint: eslint]
> 
> Parsing error: Unexpected character '#'

This could be:

```
Parsing error: Unexpected character '#' [eslint: parsing]
```

---

> > 35: extra_table=[] # missing whitespace around operator E225 (flake8); at least two spaces before inline comment E261 (flake8); line too long (126 > 99 characters) E501 (flake8)
> 
> Error: Linting issue [mozlint: flake8]
> 
> missing whitespace around operator

This could be:

```
Error: Missing whitespace around operator [flake8: E225]
```

Please let me know what you think about these suggested improvements.

**Comment by ahal** [comment]
I assume you're getting mozlint to output JSON and then formatting that. If you like, we could add a "review" formatter directly in mozlint, so you'd run something like:
./mach lint --format review

Then, just print whatever it returns. The downside is that the format would be defined in-tree though, so you may not want to go this route.

**Comment by La0** [comment]
@ahal Thanks but the bot needs to know about line numbers and error level to filter issues to publish. So the `json` output format is already a great mean to do that.
