### ISSUE TITLE
shipit_uplift: Use calixte's parsepatch library instead of whatthepatch

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#766]
CC @calixteman

**Comment by Calixte** [comment]
You are @mentioning the wrong Calixte.

**Comment by marco-c** [comment]
> You are @mentioning the wrong Calixte.

Right, CC @calixteman :)

**Comment by calixteman** [comment]
ah ah !
this first name is so rare...

**Comment by marco-c** [comment]
Closed because we are not parsing patches anymore (see #838).
