### ISSUE TITLE
shipit_code_coverage: Upload the chunk mapping as an artifact and index the coverage task on the TaskCluster index

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#769]
Right now the file is temporarily uploaded in a GitHub repository. To actually make it usable in production, we should upload the file as an artifact and index the coverage task so that clients can find it.

**Comment by garbas** [comment]
@marco-c Lets assume also other tasks will use index and to select namespace

we are already using: https://tools.taskcluster.net/index/project.releng.services.requests

maybe a namespace for `shipit_code_coverage` project should be `project.releng.services.project.shipit_code_coverage`?

so basically following this `project.releng.services.project.<project_name>` convention
