### ISSUE TITLE
shipit_static_analysis: eslint incorrectly report ok() as not defined

### ISSUE THREAD

**Issue by na-g** [mozilla-releng/services#776]
**MozReview URL:** https://reviewboard.mozilla.org/r/…

**Problem:** "ok(...)" is defined. A search on MDN leads me to believe that it is provided in the mochitest environment by https://dxr.mozilla.org/mozilla-central/source/testing/mochitest/tests/SimpleTest/SimpleTest.js.  Link: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Mochitest

**Comment by sylvestre** [comment]
Do you have an example where you see that? Thanks

**Comment by na-g** [comment]
@sylvestre, sorry, I didn't notice the review URL was truncated: https://reviewboard.mozilla.org/r/214554/#comment277978

**Comment by Standard8** [comment]
dom/media/tests don't actually get eslint run on them at the moment - at least not the .html files:

https://searchfox.org/mozilla-central/rev/062e1cf551f5bf3f0af33671b818f75a55ac497b/.eslintignore#242-243

So I think this is probably the rest of #788, which has now been deployed.

@na-g if you update the patch & re-push, then I think this might go away.

**Comment by na-g** [comment]
Thanks @Standard8, I will give it a whirl.

**Comment by La0** [comment]
I just checked your patch with the last version of the code review bot: no more issues detected (indeed fixed by #788).
Closing this issue.
