### ISSUE TITLE
shipit_static_analysis: add shellcheck

### ISSUE THREAD

**Issue by srfraser** [mozilla-releng/services#785]
From https://reviewboard.mozilla.org/r/214922/#comment278356 I've been advised to ask for shellcheck to be added to a reviewbot here. I'm unclear on the details of how to use it. Presumably the request itself makes sense? :) 

https://shellcheck.net/, but it's in apt repositories.

**Comment by La0** [comment]
Hi Simon, Thanks for your input.
Shellcheck looks like a great addition to our static analysis bot. It seems available as a Nix package, so it could be included in the next release.

@sylvestre do you agree on adding shellcheck ?

**Comment by sylvestre** [comment]
200% 👍
