### ISSUE TITLE
shipit_static_analysis: reviewbot uses --no-ignore with eslint

### ISSUE THREAD

**Issue by ahal** [mozilla-releng/services#788]
**MozReview URL:** https://reviewboard.mozilla.org/r/214284/

**Problem:** I noticed that reviewbot uses --no-ignore with eslint:
https://github.com/mozilla-releng/services/blob/master/src/shipit_static_analysis/shipit_static_analysis/lint.py#L128

This results in reviews being posted to files that would otherwise be ignored when running eslint locally (such as the example linked above). This means developers could run ./mach lint locally, see no errors, push to review, and have them posted.

I think the reason this was initially added was because eslint generates a dummy 'warning' error when it ignores a file, which would probably trip up the reviewbot. I think we'll need to explicitly detect + ignore this dummy warning error, either in the reviewbot, or in tools/lint/eslint. It probably makes sense to ignore this from in-tree. I'll file a bug.

So steps to fix this will be:
1) Ignore the dummy warning when eslint ignores a file
2) Remove --no-ignore

**Comment by ahal** [comment]
Oh cancel that. The proper fix here is to pass in --quiet instead of --no-ignore. We pass in --quiet for eslint both in CI and in the push hook, so we should do the same here. I'll submit a PR.

**Comment by La0** [comment]
Thanks @ahal for your patch, i just merged it.
