### ISSUE TITLE
shipit_static_analysis: eslint is failing to parse files with ifdefs

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla-releng/services#795]
Ifdef's are causing linting issues on my review:
https://reviewboard.mozilla.org/r/212562/#review221642
`Error: Parsing error: Unexpected character '#' [eslint: None]`

Many of the errors I was given were in ignored files, this is aggressive IMO especially as try won't fail either here.

**Comment by sylvestre** [comment]
@ahal is that on your side or ours?

**Comment by La0** [comment]
I think it's on our side (related to #788). I just pushed @ahal fix to production, it should be live in ~ 30 minutes.

**Comment by ahal** [comment]
Yeah, that fix should prevent ignored files from being linted. This can probably be resolved.

**Comment by sylvestre** [comment]
Thanks!
