### ISSUE TITLE
shipit_code_coverage: Store size and first and last modification of files in the zero coverage report

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#803]

**Comment by rhcu** [comment]
Hi Marco!
I have tried to fix this issue, and have already an idea how to do this in `reports_generator.py` file. However, I was unable to install the project locally. Specifically, I have read https://docs.mozilla-releng.net/develop/contribute.html guide and installed Docker.  However, when I try to run the `./please run <my-project-name>` command, there is such problem: `download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/b27ysyci6wkimp2zi676jz9607fliyxv.narinfo’ (Curl error 6)`
I have tried to find a solution on NixOS GitHub forum but it is full of comments about the same issue: https://github.com/NixOS/nixpkgs/issues/14874. 
Can you help to resolve this?

**Comment by garbas** [comment]
@rhcu feel free to drop on #shipit IRC channel (irc.mozilla.org) where we can assist you in real time and unblock you.

**Comment by garbas** [comment]
@rhcu hey! i tried to reply to you but it looks like you went away. Could you provide which OS are you using? and from where are you connecting (from which country)?

**Comment by garbas** [comment]
@rhcu also did you install docker or nix? i think that would give me enough information to help you

**Comment by rhcu** [comment]
@garbas Sorry for leaving. I have installed Docker (used this guide: https://docs.docker.com/get-started/) because I was not able to install nix (used this guide: https://docs.mozilla-releng.net/develop/install-nix.html#develop-install-nix). I use Ubuntu 16.04 OS and connecting from Kazakhstan.
