### ISSUE TITLE
shipit_code_coverage: Store zero coverage files and functions in a single JSON file

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#804]
Right now, we have a zero_coverage_files.json with an array of file paths and a zero_coverage_functions.json with an array of objects with the format:
```
{
    'name': FILE_PATH,
    'funcs': NUMBER_OF_UNCOVERED_FUNCTIONS,
}
```

We should store everything in a single file, containing an array of objects with the format:
```
{
    'name': FILE_PATH,
    'funcs': NUMBER_OF_UNCOVERED_FUNCTIONS,
    'uncovered': TRUE if uncovered, FALSE if covered,
}
```

**Comment by akankshanayak2111** [comment]
I am working on this issue :)

**Comment by akankshanayak2111** [comment]
https://github.com/mozilla-releng/services/pull/943 

I have raised a PR for this. Quick question, do I need to add any tests for my code changes ?

**Comment by marco-c** [comment]
> I have raised a PR for this. Quick question, do I need to add any tests for my code changes ?

I've replied in the PR, you can just update the preexisting tests.
