### ISSUE TITLE
shipit_frontend, shipit_uplift: Remove coverage by directory view and API

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#837]
It is no longer used.

**Comment by Sush0512** [comment]
Dear @marco-c,
I started working on this issue. I found the file `coverage_by_dir_impl.py` and `api.py` in `shipit_uplift `folder.
By `remove coverage by directory view and API`, do you mean to  delete the above mentioned files and its dependencies from generating coverage?

**Comment by marco-c** [comment]
Yes, coverage_by_dir_impl and the code that uses it in api.py (and the definition in api.yml) should be removed.

Also, the coverage code in src/shipit_frontend/src should be removed too.
