### ISSUE TITLE
`grcov` errored with error -9 in all recent code coverage tasks

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#897]
Maybe caused by the recent package updates.

**Comment by marco-c** [comment]
There's not enough info in the logs, but probably the process was killed because it run out of memory.
Maybe the update somehow increased memory usage.

**Comment by marco-c** [comment]
Reverting the update on staging fixed the problem. CC @garbas

**Comment by garbas** [comment]
@marco-c I assume you opened #898 for this reason, right?

**Comment by marco-c** [comment]
> @marco-c I assume you opened #898 for this reason, right?

Not really, m4 and m5 have the same amount of memory available.

**Comment by marco-c** [comment]
If we wanted to fix this by increasing the amount of memory, we would need to switch from m4.large to m4.xlarge I guess (but the cost would be 2x).

**Comment by marco-c** [comment]
For now, I've switched to an xlarge instance. I don't know if it's worth it investigating this more.

**Comment by garbas** [comment]
would it be possible to switch to xlarge instance only for the troubling taskcluster task?

**Comment by marco-c** [comment]
Yes, I switched to xlarge only the code coverage task. We have the `releng-svc` and `releng-svc-compute` provisioners, I switched `releng-svc-compute` (only used by code coverage currently) to xlarge.

**Comment by marco-c** [comment]
I'm pretty sure this was OOM. I've switched to a memory-optimized instance and this is no longer happening.

https://bugzilla.mozilla.org/show_bug.cgi?id=1454629 should help even more (after that bug, we might probably go back to a m5.large instance).

**Comment by marco-c** [comment]
(it would be interesting to know why the memory usage increases are so correlated with package updates)
