### ISSUE TITLE
Switch to m5 instance types for our worker types

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#898]
This could especially help static analysis, since the new instance types should have improved network performance.

**Comment by garbas** [comment]
@marco-c maybe we could only switch to m5 instance type for jobs that we know need more memory. 

/me is not sure how worker types work. need to refresh my memory

**Comment by marco-c** [comment]
I filed this more for static analysis, where we need a fast feedback cycle (and cloning from hgmo is a good chunk of the analysis). m5 have increased network performance (and lower cost?).

**Comment by marco-c** [comment]
m5 is just the new iteration of the general purpose instance types, if I understand correctly.

**Comment by marco-c** [comment]
I think we should do this, @garbas @La0. The m5 instances are cheaper and faster than the m4, so there's no point in not switching (unless their different characteristics cause issues).

**Comment by marco-c** [comment]
I've just changed the instance type from m4 to m5 for `releng-svc`. Let's see if things break.

**Comment by marco-c** [comment]
Everything seems to be working fine!
