### ISSUE TITLE
Trychooser suggest target macosx64-st-an which doesn't work.

### ISSUE THREAD

**Issue by nical** [mozilla-releng/services#908]
In trychooser, tick `macosx64 static analysis`, and it will add `macosx64-st-an` to the try command.

I suppose the target was removed or renamed in the CI but not yet in trychooser, see: https://treeherder.mozilla.org/#/jobs?repo=try&revision=09b9853ef5bf1a2246a8078b8f29305649b1d08e

**Comment by garbas** [comment]
fixed in  #937
