### ISSUE TITLE
`deadline` and `expires` fields are deprecated and will soon be removed

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#915]
We should fix our projects to stop using these fields in hook definitions. They are going to be moved to the `task` template: https://docs.taskcluster.net/reference/core/taskcluster-hooks/docs/firing-hooks#task-times.

See https://github.com/taskcluster/taskcluster-hooks/pull/85.

@garbas @La0 I think we will need a new release for this.

**Comment by La0** [comment]
`expires` is the field that broke static analysis last weekend.
