### ISSUE TITLE
Remove utils.mkdir and use makedirs everywhere

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#956]
Since Python 3.2, there's a `exist_ok` parameter that allows to ignore errors due to an already existing directory. So, we can drop utils.mkdir and use makedirs with exist_ok=True everywhere.

**Comment by fiennyangeln** [comment]
I want to take this issue.

**Comment by garbas** [comment]
@marco-c should this be also a flake8 check?

**Comment by marco-c** [comment]
I think we don't need the flake8 check, as we will remove utils.mkdir altogether.

**Comment by garbas** [comment]
i know we are going to remove it now, but latter somebody could use it and having a check would point them in the right direction what else to use.

**Comment by marco-c** [comment]
If we remove it, nobody would be able to use it (unless they reimplement it from scratch).
We could add a check that disallows something like:
```
    try:
        os.mkdir(path)
    except OSError as e:
        if e.errno != errno.EEXIST:
            raise
```
but a check to disallow utils.mkdir would be unnecessary if we remove utils.mkdir altogether.
I don't know how easy it would be to implement such a check, as one could write the same code in slightly different ways (and I've never written a flake8 check, so I have no idea how easy/hard it is in general).

**Comment by garbas** [comment]
@marco-c sorry i was constantly reading `utils.mkdir` as `os.mkdir` and i want to add a check to avoid `os.mkdir`, but i see it is impossible.
