### ISSUE TITLE
add more flake8 checks

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#96]
## Checks to add:

- [x] Use [flake8-coding](https://pypi.python.org/pypi/flake8-coding) to ensure every file has utf8 encoding defined, #381 
- [x] Use [flake8-quotes](https://pypi.python.org/pypi/flake8-quotes) to only use single quotes, #389 
- [ ] Use [flake8-isort](https://pypi.python.org/pypi/flake8-isort) to enforce ordering of the imports
- [ ] Use [flake8-ownership](https://pypi.python.org/pypi/flake8-ownership) to ensure every file has the license at the top
- [ ] Use [flake8-future-import](https://pypi.python.org/pypi/flake8-future-import) to ensure that every file has ``from __future__ import absolute_import`` at the top
- [ ] Use [flake8-debugger](https://pypi.python.org/pypi/flake8-debugger) to make sure ipdb/pdb statements are not in code
- [ ] add initial support for mypy via [flake8-mypy](https://pypi.python.org/pypi/flake8-mypy)
- [ ] warn about TODO statements, since we should convert them to tickets, via [flake8-todo](https://pypi.python.org/pypi/flake8-todo)
- [ ] lint docstrings as well via [flake8-docstrings](https://pypi.python.org/pypi/flake8-docstrings)

... if you think we should do also other checks please suggest in the comments

**Comment by ibrahimsharaf** [comment]
Hello @garbas, I want to work on this, how can I start?

**Comment by garbas** [comment]
Hi @ibrahimsharaf,

This is a multi part issue, I will clarify the instructions in the description above and please let me know if they make more sense.

Not to be overwhelmed it would be good to start on a subsection of the code, I suggest ``src/releng_treestatus``. We can later apply the same steps to other projects in ``src/`` folder.

You will find ``requirements.txt`` and ``requirements-dev.txt`` in the above mentioned folder. Bootstrapping the project should be as any other python projects (virtualenv + pip). Once everything is installed you should be able to run ``flake8 --exclude=nix_run_setup.py,migrations/,build/`` which is a tool we use to lint our code.

**Comment by garbas** [comment]
Hi @ibrahimsharaf, I hope I didn't overwhelm you with the instructions :)

**Comment by ibrahimsharaf** [comment]
Hello @garbas, sorry I am in final exams period, will get back to you after then :)

**Comment by garbas** [comment]
As of today @harikishen took over the work of this ticket and i created a branch for this work to start (read the issue description)

@ibrahimsharaf since this is a multi stage ticket ping me when you are back and i'll update you with the progress and you can join the effort at any stage.

**Comment by harikishen** [comment]
@garbas what is the intended ordering for flake8-isort ?

**Comment by harikishen** [comment]
@garbas what do you think of using [flake8-ownership](https://pypi.python.org/pypi/flake8-ownership/0.10.2) for licenses ?

**Comment by garbas** [comment]
a long overdue answer. flake8-ownership looks like a solution for licenses.

**Comment by garbas** [comment]
done in #995
