### ISSUE TITLE
Support multiple deployments per project

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#962]
Currently we can only define one deployment per project. Deployments are defined in `lib/please_cli/please_cli/config.py`. 

We need to turn that definition into a list and make sure that when generating decision task create tasks for each deployment.

We also need to consider having a dependencies between deployment. For example we might like to first push to docker image to docker registry and then create a takcluster hook which requires to have that image present before it can run.

**Comment by garbas** [comment]
This was partially fixed in #1061 but the rest would be fixed in #1219
