### ISSUE TITLE
Remove get_directory_coverage functions from shipit_uplift

### ISSUE THREAD

**Issue by marco-c** [mozilla-releng/services#971]
Now that #837 has been fixed by #952, we can remove the **get_directory_coverage** functions from src/shipit_uplift/shipit_uplift/coverage.py as they are unused.

**Comment by marco-c** [comment]
@Sush0512 do you want to take this on, to complete the removal you started?

**Comment by Sush0512** [comment]
Sure. Thanks!

**Comment by marco-c** [comment]
@Sush0512 the simplest thing to do at the moment, if **./please check shipit-uplift** terminates with the same error, would be to just submit the PR and let Taskcluster run the tests for you.
