### ISSUE TITLE
generate correct route53.tf file

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#979]
there is a please command which generates (incorrect) terraform/base/route53.tf file.

```
$ ./please tools terraform-route53-config > route53.tf 
```

The code for the above command is located here:
https://github.com/mozilla-releng/services/blob/master/lib/please_cli/please_cli/terraform_route53_config.py

File which we need to generate is located here: 
https://github.com/mozilla-releng/build-cloud-tools/blob/master/terraform/base/route53.tf

**Comment by mutterroland** [comment]
I started looking into it. I'll be back with updates.

**Comment by garbas** [comment]
fixed in #1028
