### ISSUE TITLE
setup services email to get production reports from sentry/datadog/papertrail/heroku/etc..

### ISSUE THREAD

**Issue by garbas** [mozilla-releng/services#991]
@La0 @marco-c @rail @lundjordan : I don't want to subscribe us to - yet another email - but I would like to have an email alias which we can use to be notified about alerts on sentry/datadog/papertrail/heroku/etc...

as people will come and go to this project it would be much easier to adjust the alias subscription then to reconfigure it in many places.

does "release-services@mozilla.com" sound ok? if not, any other suggestions?

**Comment by rail** [comment]
Sounds sane to me. To make things easier, you can ask for a google group for this email, so people can subscribe/unsubscribe or browse.

**Comment by garbas** [comment]
@rail who should I ask for creation of google group?

**Comment by rail** [comment]
Just file a Hub request. I can give you the exact link in IRC.

**Comment by garbas** [comment]
@rail tnx found it. invitations soon follows
