### ISSUE TITLE
shipit_static_analysis: Problem with an automated review

### ISSUE THREAD

**Issue by kmaglione** [mozilla-releng/services#997]
**MozReview URL:** https://reviewboard.mozilla.org/r/230052/#review236310

**Problem:** I see this repeatedly. The review bot reports that the lower-cased version of a mixed-case variable name is undefined:

```
> +  ok(isExtensionInBootstrappedList(profileDir, a1.id));

Error: 'isextensioninbootstrappedlist' is not defined. [eslint: no-undef]
```

Which is true. `isextensioninbootstrappedlist` is not defined. But `isExtensionInBootstrappedList` is, and the latter is what the code actually uses.

**Comment by sylvestre** [comment]
@ahal @Standard8 I think this is an issue with mozlint itself, right?

**Comment by kmaglione** [comment]
For what it's worth, these errors don't show up with `mach lint`, or the commit hook, or in try runs. Only in static analysis bot reviews.

**Comment by jankeromnes** [comment]
@La0 found the culprit: https://github.com/mozilla-releng/services/blob/67c197a00e47af3bb92f3d2696a1909e6f3b3dd6/src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py#L269
